
# This file was generated by 'versioneer.py' (0.10+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.7.5'
version_full = 'a4bd4f42fc7349ce05f54bcc9570c117bc9a263c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

