__version__ = "0.1.6"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.1.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '86a61aa0b0fbe4c85a6c419301a77ccab53ff13e'
__git_head_subject__ = 'HIPVM-665 reset property collector when merge fails'
__git_head_message__ = ''
__git_dirty_diff__ = ''