
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.3'
version_full = '4d974d9a4d5584080622319335d987ec7aa68cdc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

