__version__ = "0.4.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.4.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '275123d9ab6d8bd9e887c7f43ffb6f13d5f68bbf'
__git_head_subject__ = 'Finished release v0.4.3.'
__git_head_message__ = '* release/v0.4.3:\n  TRIVIAL adapting to Logbook-0.8.1\n  buildout.cfg: changed isolated python version to v2.7.6.21\n  buildout.cfg: changed isolated python version to v2.7.6.20\n  buildout.cfg: changed isolated python version to v2.7.6.19'
__git_dirty_diff__ = ''