
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.3.3'
version_full = '1a22565e24f81247f8c9e498541555460c0db6a0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

