
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4'
version_full = '682967ff9afea0987672fcb46d4ce0d6962130d9'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

