
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.5'
version_full = '666b5c13d5bc51d48447374a638817c64b309bb6'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

