
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4'
version_full = '404c5f894fe4a3369622047f3950ec17d8a5c1ef'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

