
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3'
version_full = '2ef7ee9129ca74b5774ad55c886b921f6f6db52b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

