
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.2'
version_full = '36af55b2f82caaacb590327eb93e589580bac85b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

