from setuptools import setup

setup(name="configreader",
    description="An easy-to-use, powerful configuration module for Python",
    long_description = open('README.rst','r').read(),
    license="MIT",
    version = "0.0.5",
    author = "Martin Ortbauer",
    author_email = "mortbauer@gmail.com",
    url = "https://github.com/mortbauer/configreader",
    py_modules = ["configreader"],
    classifiers=[
          "Development Status :: 3 - Alpha",
          "Intended Audience :: Developers",
          "License :: OSI Approved :: MIT License",
          "Programming Language :: Python",
          "Topic :: Utilities",
          "Natural Language :: English",
          "Operating System :: OS Independent",
          "Programming Language :: Python",
          "Programming Language :: Python :: 2",
          "Programming Language :: Python :: 2.6",
          "Programming Language :: Python :: 2.7",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3.3",
          "Programming Language :: Python :: 3.4 ",
    ],
    )
