
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.1'
version_full = 'd33ab02c1d3518c5bc1edfa376870a92d5d3c62a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

