
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.2'
version_full = 'f9cb120a0963dab556155be9b6f26117c5bb910f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

