# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/geoff/work/baserip/baserip/ui/br_mainwindow.ui'
#
# Created: Wed Dec 17 20:34:54 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BR_MainWindow(object):
    def setupUi(self, BR_MainWindow):
        BR_MainWindow.setObjectName(_fromUtf8("BR_MainWindow"))
        BR_MainWindow.resize(576, 665)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BR_MainWindow.sizePolicy().hasHeightForWidth())
        BR_MainWindow.setSizePolicy(sizePolicy)
        BR_MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/baserip.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BR_MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(BR_MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSource = QtGui.QWidget()
        self.tabSource.setObjectName(_fromUtf8("tabSource"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabSource)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.tabSource)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.DVDTree = SourceTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.DVDTree.sizePolicy().hasHeightForWidth())
        self.DVDTree.setSizePolicy(sizePolicy)
        self.DVDTree.setObjectName(_fromUtf8("DVDTree"))
        self.textTrackInfo = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.textTrackInfo.sizePolicy().hasHeightForWidth())
        self.textTrackInfo.setSizePolicy(sizePolicy)
        self.textTrackInfo.setUndoRedoEnabled(False)
        self.textTrackInfo.setReadOnly(True)
        self.textTrackInfo.setObjectName(_fromUtf8("textTrackInfo"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tabSource, _fromUtf8(""))
        self.tabSubtitles = QtGui.QWidget()
        self.tabSubtitles.setObjectName(_fromUtf8("tabSubtitles"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSubtitles)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.SscrollArea = QtGui.QScrollArea(self.tabSubtitles)
        self.SscrollArea.setWidgetResizable(True)
        self.SscrollArea.setObjectName(_fromUtf8("SscrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 94, 24))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.SscrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.SscrollArea)
        self.tabWidget.addTab(self.tabSubtitles, _fromUtf8(""))
        self.tabAudio = QtGui.QWidget()
        self.tabAudio.setObjectName(_fromUtf8("tabAudio"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabAudio)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.AscrollArea = QtGui.QScrollArea(self.tabAudio)
        self.AscrollArea.setWidgetResizable(True)
        self.AscrollArea.setObjectName(_fromUtf8("AscrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 94, 24))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.AscrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.AscrollArea)
        self.tabWidget.addTab(self.tabAudio, _fromUtf8(""))
        self.tabVideo = QtGui.QWidget()
        self.tabVideo.setObjectName(_fromUtf8("tabVideo"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabVideo)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.VscrollArea = QtGui.QScrollArea(self.tabVideo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.VscrollArea.sizePolicy().hasHeightForWidth())
        self.VscrollArea.setSizePolicy(sizePolicy)
        self.VscrollArea.setWidgetResizable(True)
        self.VscrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.VscrollArea.setObjectName(_fromUtf8("VscrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 94, 24))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.VscrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.VscrollArea)
        self.tabWidget.addTab(self.tabVideo, _fromUtf8(""))
        self.tabFormat = QtGui.QWidget()
        self.tabFormat.setObjectName(_fromUtf8("tabFormat"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabFormat)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.FscrollArea = QtGui.QScrollArea(self.tabFormat)
        self.FscrollArea.setWidgetResizable(True)
        self.FscrollArea.setObjectName(_fromUtf8("FscrollArea"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 94, 24))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.FscrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.addWidget(self.FscrollArea)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.tabFormat)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.op_dir_edit = QtGui.QLineEdit(self.tabFormat)
        self.op_dir_edit.setObjectName(_fromUtf8("op_dir_edit"))
        self.horizontalLayout_2.addWidget(self.op_dir_edit)
        self.btnSelDir = QtGui.QPushButton(self.tabFormat)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/folder-blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelDir.setIcon(icon1)
        self.btnSelDir.setObjectName(_fromUtf8("btnSelDir"))
        self.horizontalLayout_2.addWidget(self.btnSelDir)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtGui.QLabel(self.tabFormat)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.op_file_edit = QtGui.QLineEdit(self.tabFormat)
        self.op_file_edit.setText(_fromUtf8(""))
        self.op_file_edit.setObjectName(_fromUtf8("op_file_edit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.op_file_edit)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.btnStart = QtGui.QPushButton(self.tabFormat)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.verticalLayout_6.addWidget(self.btnStart)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tabFormat, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnExit = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon2)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.horizontalLayout.addWidget(self.btnExit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        BR_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(BR_MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BR_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BR_MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BR_MainWindow)

    def retranslateUi(self, BR_MainWindow):
        BR_MainWindow.setWindowTitle(_translate("BR_MainWindow", "Baserip", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSource), _translate("BR_MainWindow", "Source", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSubtitles), _translate("BR_MainWindow", "Subtitles", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAudio), _translate("BR_MainWindow", "Audio", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVideo), _translate("BR_MainWindow", "Video", None))
        self.label.setText(_translate("BR_MainWindow", "Output Directory:", None))
        self.op_dir_edit.setToolTip(_translate("BR_MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">%T</span> - Title of the track</p><p><span style=\" font-weight:600;\">%N</span> - Number of the selected track (useful for batch encoding)</p><p><span style=\" font-weight:600;\">%L</span> - Length of the selected track</p><p><span style=\" font-weight:600;\">%f </span>- The first letter of the title (useful for organisation)</p></body></html>", None))
        self.btnSelDir.setText(_translate("BR_MainWindow", "Select", None))
        self.label_2.setText(_translate("BR_MainWindow", "File Name:", None))
        self.op_file_edit.setToolTip(_translate("BR_MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">%T</span> - Title of the track</p><p><span style=\" font-weight:600;\">%N</span> - Number of the selected track (useful for batch encoding)</p><p><span style=\" font-weight:600;\">%L</span> - Length of the selected track</p><p><span style=\" font-weight:600;\">%f </span>- The first letter of the title (useful for organisation)</p></body></html>", None))
        self.btnStart.setText(_translate("BR_MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFormat), _translate("BR_MainWindow", "Format", None))
        self.btnExit.setText(_translate("BR_MainWindow", "Exit", None))

from baserip.forms import SourceTreeView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    BR_MainWindow = QtGui.QMainWindow()
    ui = Ui_BR_MainWindow()
    ui.setupUi(BR_MainWindow)
    BR_MainWindow.show()
    sys.exit(app.exec_())

