
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.3'
version_full = 'a92a7081693ad76c13715b637870a66d80e5b946'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

