
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4rc1'
version_full = 'b25115d045b516179c7e7e74c6712fa0440fbe8c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

