
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.4'
version_full = 'b02308e6ea821b08b734fe56381cd1d960cce076'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

