# -*- coding: UTF-8 -*-
# Copyright 2014 Luc Saffre
# This file is part of the commondata library.
# The commondata library is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
# The commondata library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with the commondata library; if not, see
# <http://www.gnu.org/licenses/>.


from __future__ import unicode_literals


def populate(pg):

    pg.set_args('fr nl de en')
    pg.province("Anvers", "Antwerpen", "Antwerpen", "Anvers")
    pg.set_args('zip_code fr nl de en')
    pg.city("2000", "Anvers", "Antwerpen", "Antwerpen", "Antwerpen")
    pg.city("2018", "Antwerpen 1", "", "", "")
    pg.city("2020", "Antwerpen 2", "", "", "")
    pg.city("2030", "Antwerpen 3", "", "", "")
    pg.city("2040", "Antwerpen 4", "", "", "")
    pg.city("2040", "Berendrecht", "", "", "")
    pg.city("2040", "Lillo", "", "", "")
    pg.city("2040", "Zandvliet", "", "", "")
    pg.city("2050", "Antwerpen 5", "", "", "")
    pg.city("2060", "Antwerpen 6", "", "", "")
    pg.city("2070", "Burcht", "", "", "")
    pg.city("2070", "Zwijndrecht", "", "", "")
    pg.city("2100", "Deurne (Antwerpen)", "", "", "")
    pg.city("2110", "Wijnegem", "", "", "")
    pg.city("2140", "Borgerhout (Antwerpen)", "", "", "")
    pg.city("2150", "Borsbeek (Antw.)", "", "", "")
    pg.city("2160", "Wommelgem", "", "", "")
    pg.city("2170", "Merksem (Antwerpen)", "", "", "")
    pg.city("2180", "Ekeren (Antwerpen)", "", "", "")
    pg.city("2200", "Herentals", "", "", "")
    pg.city("2200", "Morkhoven", "", "", "")
    pg.city("2200", "Noorderwijk", "", "", "")
    pg.city("2220", "Hallaar", "", "", "")
    pg.city("2220", "Heist-Op-Den-Berg", "", "", "")
    pg.city("2221", "Booischot", "", "", "")
    pg.city("2222", "Itegem", "", "", "")
    pg.city("2222", "Wiekevorst", "", "", "")
    pg.city("2223", "Schriek", "", "", "")
    pg.city("2230", "Herselt", "", "", "")
    pg.city("2230", "Ramsel", "", "", "")
    pg.city("2235", "Houtvenne", "", "", "")
    pg.city("2235", "Hulshout", "", "", "")
    pg.city("2235", "Westmeerbeek", "", "", "")
    pg.city("2240", "Massenhoven", "", "", "")
    pg.city("2240", "Viersel", "", "", "")
    pg.city("2240", "Zandhoven", "", "", "")
    pg.city("2242", "Pulderbos", "", "", "")
    pg.city("2243", "Pulle", "", "", "")
    pg.city("2250", "Olen", "", "", "")
    pg.city("2260", "Oevel", "", "", "")
    pg.city("2260", "Tongerlo (Antw.)", "", "", "")
    pg.city("2260", "Westerlo", "", "", "")
    pg.city("2260", "Zoerle-Parwijs", "", "", "")
    pg.city("2270", "Herenthout", "", "", "")
    pg.city("2275", "Gierle", "", "", "")
    pg.city("2275", "Lille", "", "", "")
    pg.city("2275", "Poederlee", "", "", "")
    pg.city("2275", "Wechelderzande", "", "", "")
    pg.city("2280", "Grobbendonk", "", "", "")
    pg.city("2288", "Bouwel", "", "", "")
    pg.city("2290", "Vorselaar", "", "", "")
    pg.city("2300", "Turnhout", "", "", "")
    pg.city("2310", "Rijkevorsel", "", "", "")
    pg.city("2320", "Hoogstraten", "", "", "")
    pg.city("2321", "Meer", "", "", "")
    pg.city("2322", "Minderhout", "", "", "")
    pg.city("2323", "Wortel", "", "", "")
    pg.city("2328", "Meerle", "", "", "")
    pg.city("2330", "Merksplas", "", "", "")
    pg.city("2340", "Beerse", "", "", "")
    pg.city("2340", "Vlimmeren", "", "", "")
    pg.city("2350", "Vosselaar", "", "", "")
    pg.city("2360", "Oud-Turnhout", "", "", "")
    pg.city("2370", "Arendonk", "", "", "")
    pg.city("2380", "Ravels", "", "", "")
    pg.city("2381", "Weelde", "", "", "")
    pg.city("2382", "Poppel", "", "", "")
    pg.city("2387", "Baarle-Hertog", "", "", "")
    pg.city("2390", "Malle", "", "", "")
    pg.city("2390", "Oostmalle", "", "", "")
    pg.city("2390", "Westmalle", "", "", "")
    pg.city("2400", "Mol", "", "", "")
    pg.city("2430", "Eindhout", "", "", "")
    pg.city("2430", "Vorst (Kempen)", "", "", "")
    pg.city("2431", "Varendonk", "", "", "")
    pg.city("2431", "Veerle", "", "", "")
    pg.city("2440", "Geel", "", "", "")
    pg.city("2450", "Meerhout", "", "", "")
    pg.city("2460", "Kasterlee", "", "", "")
    pg.city("2460", "Lichtaart", "", "", "")
    pg.city("2460", "Tielen", "", "", "")
    pg.city("2470", "Retie", "", "", "")
    pg.city("2480", "Dessel", "", "", "")
    pg.city("2490", "Balen", "", "", "")
    pg.city("2491", "Olmen", "", "", "")
    pg.city("2500", "Koningshooikt", "", "", "")
    pg.city("2500", "Lier", "", "", "")
    pg.city("2520", "Broechem", "", "", "")
    pg.city("2520", "Emblem", "", "", "")
    pg.city("2520", "Oelegem", "", "", "")
    pg.city("2520", "Ranst", "", "", "")
    pg.city("2530", "Boechout", "", "", "")
    pg.city("2531", "Vremde", "", "", "")
    pg.city("2540", "Hove", "", "", "")
    pg.city("2547", "Lint", "", "", "")
    pg.city("2550", "Kontich", "", "", "")
    pg.city("2550", "Waarloos", "", "", "")
    pg.city("2560", "Bevel", "", "", "")
    pg.city("2560", "Kessel", "", "", "")
    pg.city("2560", "Nijlen", "", "", "")
    pg.city("2570", "Duffel", "", "", "")
    pg.city("2580", "Beerzel", "", "", "")
    pg.city("2580", "Putte", "", "", "")
    pg.city("2590", "Berlaar", "", "", "")
    pg.city("2590", "Gestel", "", "", "")
    pg.city("2600", "Berchem (Antwerpen)", "", "", "")
    pg.city("2610", "Wilrijk (Antwerpen)", "", "", "")
    pg.city("2620", "Hemiksem", "", "", "")
    pg.city("2627", "Schelle", "", "", "")
    pg.city("2630", "Aartselaar", "", "", "")
    pg.city("2640", "Mortsel", "", "", "")
    pg.city("2650", "Edegem", "", "", "")
    pg.city("2660", "Hoboken (Antwerpen)", "", "", "")
    pg.city("2800", "Walem", "", "", "")
    pg.city("2800", "Malines", "Mechelen", "Mechelen", "Mechelen")
    pg.city("2801", "Heffen", "", "", "")
    pg.city("2811", "Hombeek", "", "", "")
    pg.city("2811", "Leest", "", "", "")
    pg.city("2812", "Muizen (Mechelen)", "", "", "")
    pg.city("2820", "Bonheiden", "", "", "")
    pg.city("2820", "Rijmenam", "", "", "")
    pg.city("2830", "Blaasveld", "", "", "")
    pg.city("2830", "Heindonk", "", "", "")
    pg.city("2830", "Tisselt", "", "", "")
    pg.city("2830", "Willebroek", "", "", "")
    pg.city("2840", "Reet", "", "", "")
    pg.city("2840", "Rumst", "", "", "")
    pg.city("2840", "Terhagen", "", "", "")
    pg.city("2845", "Niel", "", "", "")
    pg.city("2850", "Boom", "", "", "")
    pg.city("2860", "Sint-Katelijne-Waver", "", "", "")
    pg.city("2861", "Onze-Lieve-Vrouw-Waver", "", "", "")
    pg.city("2870", "Breendonk", "", "", "")
    pg.city("2870", "Liezele", "", "", "")
    pg.city("2870", "Puurs", "", "", "")
    pg.city("2870", "Ruisbroek (Antw.)", "", "", "")
    pg.city("2880", "Bornem", "", "", "")
    pg.city("2880", "Hingene", "", "", "")
    pg.city("2880", "Mariekerke (Bornem)", "", "", "")
    pg.city("2880", "Weert", "", "", "")
    pg.city("2890", "Lippelo", "", "", "")
    pg.city("2890", "Oppuurs", "", "", "")
    pg.city("2890", "Sint-Amands", "", "", "")
    pg.city("2900", "Schoten", "", "", "")
    pg.city("2910", "Essen", "", "", "")
    pg.city("2920", "Kalmthout", "", "", "")
    pg.city("2930", "Brasschaat", "", "", "")
    pg.city("2940", "Hoevenen", "", "", "")
    pg.city("2940", "Stabroek", "", "", "")
    pg.city("2950", "Kapellen (Antw.)", "", "", "")
    pg.city("2960", "Brecht", "", "", "")
    pg.city("2960", "Sint-Job-in-'t-Goor", "", "", "")
    pg.city("2960", "Sint-Lenaerts", "", "", "")
    pg.city("2970", "'s Gravenwezel", "", "", "")
    pg.city("2970", "Schilde", "", "", "")
    pg.city("2980", "Halle (Kempen)", "", "", "")
    pg.city("2980", "Zoersel", "", "", "")
    pg.city("2990", "Loenhout", "", "", "")
    pg.city("2990", "Wuustwezel", "", "", "")
