# -*- coding: UTF-8 -*-
# Copyright 2014 Luc Saffre
# This file is part of the commondata library.
# The commondata library is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
# The commondata library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with the commondata library; if not, see
# <http://www.gnu.org/licenses/>.


from __future__ import unicode_literals


def populate(pg):

    pg.set_args('zip_code fr nl de en')

    pg.city("1000", "Bruxelles", "Brussel", "Brüssel", "Brussels")
    pg.city("1020", "Laeken", "", "", "")
    pg.city("1030", "Schaerbeek", "Schaarbeek", "", "")
    pg.city("1040", "Etterbeek")
    pg.city("1050", "Ixelles", "Elsene")
    pg.city("1060", "Saint-Gilles", "Sint-Gillis", "", "")
    pg.city("1070", "Anderlecht")
    pg.city("1080", "Molenbeek-Saint-Jean", "Sint-Jans-Molenbeek", "", "")
    pg.city("1081", "Koekelberg")
    pg.city("1082", "Berchem-Sainte-Agathe", "Sint-Agatha-Berchem")
    pg.city("1083", "Ganshoren", "", "", "")
    pg.city("1090", "Jette", "", "", "")
    pg.city("1120", "Neder-over-Heembeek", "", "", "")
    pg.city("1140", "Evere")
    pg.city("1150", "Woluwé-Saint-Pierre", "Sint-Pieters-Woluwe", "", "")
    pg.city("1160", "Auderghem", "Oudergem", "", "")
    pg.city("1170", "Watermael-Boitsfort", "Watermaal-Bosvoorde", "", "")
    pg.city("1180", "Uccle", "Ukkel")
    pg.city("1190", "Forest", "Vorst")
    pg.city("1200", "Woluwé-Saint-Lambert", "Sint-Lambrechts-Woluwe")
    pg.city("1210", "Saint-Josse-ten-Noode", "Sint-Joost-ten-Node", "", "")

    pg.city("1500", "Halle", "Hal", "Halle", "Halle")
    pg.city("1501", "Buizingen", "", "", "")
    pg.city("1502", "Lembeek", "", "", "")
    pg.city("1540", "Herfelingen", "", "", "")
    pg.city("1540", "Herne", "", "", "")
    pg.city("1541", "Sint-Pieters-Kapelle (Bt.)", "", "", "")
    pg.city("1547", "Biévène", "", "", "")
    pg.city("1547", "Biévène", "Bever", "Bever", "Bever")
    pg.city("1560", "Hoeilaart", "", "", "")
    pg.city("1570", "Tollembeek", "", "", "")
    pg.city("1570", "Vollezele", "", "", "")
    pg.city("1570", "Gammerages", "Galmaarden", "Galmaarden", "Galmaarden")
    pg.city("1600", "Oudenaken", "", "", "")
    pg.city("1600", "Sint-Laureins-Berchem", "", "", "")
    pg.city("1600", "Sint-Pieters-Leeuw", "", "", "")
    pg.city("1601", "Ruisbroek (Bt.)", "", "", "")
    pg.city("1602", "Vlezenbeek", "", "", "")
    pg.city("1620", "Drogenbos", "", "", "")
    pg.city("1630", "Linkebeek", "", "", "")
    pg.city("1640", "Rhode-Saint-Genèse", "", "", "")
    pg.city("1640", "Sint-Genesius-Rode", "", "", "")
    pg.city("1650", "Beersel", "", "", "")
    pg.city("1651", "Lot", "", "", "")
    pg.city("1652", "Alsemberg", "", "", "")
    pg.city("1653", "Dworp", "", "", "")
    pg.city("1654", "Huizingen", "", "", "")
    pg.city("1670", "Bogaarden", "", "", "")
    pg.city("1670", "Heikruis", "", "", "")
    pg.city("1670", "Pepingen", "", "", "")
    pg.city("1671", "Elingen", "", "", "")
    pg.city("1673", "Beert", "", "", "")
    pg.city("1674", "Bellingen", "", "", "")
    pg.city("1700", "Dilbeek", "", "", "")
    pg.city("1700", "Sint-Martens-Bodegem", "", "", "")
    pg.city("1700", "Sint-Ulriks-Kapelle", "", "", "")
    pg.city("1701", "Itterbeek", "", "", "")
    pg.city("1702", "Groot-Bijgaarden", "", "", "")
    pg.city("1703", "Schepdaal", "", "", "")
    pg.city("1730", "Asse", "", "", "")
    pg.city("1730", "Bekkerzeel", "", "", "")
    pg.city("1730", "Kobbegem", "", "", "")
    pg.city("1730", "Mollem", "", "", "")
    pg.city("1731", "Relegem", "", "", "")
    pg.city("1731", "Zellik", "", "", "")
    pg.city("1740", "Ternat", "", "", "")
    pg.city("1741", "Wambeek", "", "", "")
    pg.city("1742", "Sint-Katherina-lombeek", "", "", "")
    pg.city("1745", "Mazenzele", "", "", "")
    pg.city("1745", "Opwijk", "", "", "")
    pg.city("1750", "Gaasbeek", "", "", "")
    pg.city("1750", "Lennik", "", "", "")
    pg.city("1750", "Sint-Kwintens-Lennik", "", "", "")
    pg.city("1750", "Sint-Martens-Lennik", "", "", "")
    pg.city("1755", "Gooik", "", "", "")
    pg.city("1755", "Kester", "", "", "")
    pg.city("1755", "Leerbeek", "", "", "")
    pg.city("1755", "Oetingen", "", "", "")
    pg.city("1760", "Onze-Lieve-Vrouw-Lombeek", "", "", "")
    pg.city("1760", "Pamel", "", "", "")
    pg.city("1760", "Roosdaal", "", "", "")
    pg.city("1760", "Strijtem", "", "", "")
    pg.city("1761", "Borchtlombeek", "", "", "")
    pg.city("1770", "Liedekerke", "", "", "")
    pg.city("1780", "Wemmel", "", "", "")
    pg.city("1785", "Brussegem", "", "", "")
    pg.city("1785", "Hamme (Bt.)", "", "", "")
    pg.city("1785", "Merchtem", "", "", "")
    pg.city("1790", "Affligem", "", "", "")
    pg.city("1790", "Essene", "", "", "")
    pg.city("1790", "Hekelgem", "", "", "")
    pg.city("1790", "Teralfene", "", "", "")
    pg.city("1800", "Peutie", "", "", "")
    pg.city("1800", "Vilvorde", "Vilvoorde", "Vilvoorde", "Vilvoorde")
    pg.city("1820", "Melsbroek", "", "", "")
    pg.city("1820", "Perk", "", "", "")
    pg.city("1820", "Steenokkerzeel", "", "", "")
    pg.city("1830", "Machelen (Bt)", "", "", "")
    pg.city("1831", "Diegem", "", "", "")
    pg.city("1840", "Londerzeel", "", "", "")
    pg.city("1840", "Malderen", "", "", "")
    pg.city("1840", "Steenhuffel", "", "", "")
    pg.city("1850", "Grimbergen", "", "", "")
    pg.city("1851", "Humbeek", "", "", "")
    pg.city("1852", "Beigem", "", "", "")
    pg.city("1853", "Strombeek-Bever", "", "", "")
    pg.city("1860", "Meise", "", "", "")
    pg.city("1861", "Wolvertem", "", "", "")
    pg.city("1880", "Kapelle-op-den-Bos", "", "", "")
    pg.city("1880", "Nieuwenrode", "", "", "")
    pg.city("1880", "Ramsdonk", "", "", "")
    pg.city("1910", "Berg (Bt.)", "", "", "")
    pg.city("1910", "Buken", "", "", "")
    pg.city("1910", "Kampenhout", "", "", "")
    pg.city("1910", "Nederokkerzeel", "", "", "")
    pg.city("1930", "Nossegem", "", "", "")
    pg.city("1930", "Zaventem", "", "", "")
    pg.city("1931", "Brucargo", "", "", "")
    pg.city("1932", "Sint-Stevens-Woluwe", "", "", "")
    pg.city("1933", "Sterrebeek", "", "", "")
    pg.city("1950", "Kraainem", "", "", "")
    pg.city("1970", "Wezembeek-Oppem", "", "", "")
    pg.city("1980", "Eppegem", "", "", "")
    pg.city("1980", "Zemst", "", "", "")
    pg.city("1981", "Hofstade (Bt.)", "", "", "")
    pg.city("1982", "Elewijt", "", "", "")
    pg.city("1982", "Weerde", "", "", "")

