# -*- coding: UTF-8 -*-
# Copyright 2014 Luc Saffre
# This file is part of the commondata library.
# The commondata library is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
# The commondata library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with the commondata library; if not, see
# <http://www.gnu.org/licenses/>.


from __future__ import unicode_literals


def populate(pg):

    pg.set_args('fr nl de en')
    pg.province("Hainaut", "Henegouwen", "Hennegau", "Hainaut")
    pg.set_args('zip_code fr nl de en')
    
    pg.city("6000", "Charleroi", "", "", "")
    pg.city("6001", "Marcinelle", "", "", "")
    pg.city("6010", "Couillet", "", "", "")
    pg.city("6020", "Dampremy", "", "", "")
    pg.city("6030", "Goutroux", "", "", "")
    pg.city("6030", "Marchienne-au-Pont", "", "", "")
    pg.city("6031", "Monceau-sur-Sambre", "", "", "")
    pg.city("6032", "Mont-sur-Marchienne", "", "", "")
    pg.city("6040", "Jumet (Charleroi)", "", "", "")
    pg.city("6041", "Gosselies", "", "", "")
    pg.city("6042", "Lodelinsart", "", "", "")
    pg.city("6043", "Ransart", "", "", "")
    pg.city("6044", "Roux", "", "", "")
    pg.city("6060", "Gilly (Charleroi)", "", "", "")
    pg.city("6061", "Montignies-sur-Sambre", "", "", "")
    pg.city("6110", "Montigny-le-Tilleul", "", "", "")
    pg.city("6111", "Landelies", "", "", "")
    pg.city("6120", "Cour-sur-Heure", "", "", "")
    pg.city("6120", "Ham-sur-Heure", "", "", "")
    pg.city("6120", "Ham-sur-Heure/Nalinnes", "", "", "")
    pg.city("6120", "Jamioulx", "", "", "")
    pg.city("6120", "Marbaix (Ht.)", "", "", "")
    pg.city("6120", "Nalinnes", "", "", "")
    pg.city("6140", "Fontaine-l'Evêque", "", "", "")
    pg.city("6141", "Forchies-la-Marche", "", "", "")
    pg.city("6142", "Leernes", "", "", "")
    pg.city("6150", "Anderlues", "", "", "")
    pg.city("6180", "Courcelles", "", "", "")
    pg.city("6181", "Gouy-lez-Piéton", "", "", "")
    pg.city("6182", "Souvret", "", "", "")
    pg.city("6183", "Trazegnies", "", "", "")
    pg.city("6200", "Bouffioulx", "", "", "")
    pg.city("6200", "Châtelet", "", "", "")
    pg.city("6200", "Châtelineau", "", "", "")
    pg.city("6210", "Frasnes-lez-Gosselies", "", "", "")
    pg.city("6210", "Rèves", "", "", "")
    pg.city("6210", "Villers-Perwin", "", "", "")
    pg.city("6210", "Wayaux", "", "", "")
    pg.city("6211", "Mellet", "", "", "")
    pg.city("6220", "Fleurus", "", "", "")
    pg.city("6220", "Heppignies", "", "", "")
    pg.city("6220", "Lambusart", "", "", "")
    pg.city("6220", "Wangenies", "", "", "")
    pg.city("6221", "Saint-Amand", "", "", "")
    pg.city("6222", "Brye", "", "", "")
    pg.city("6223", "Wagnelée", "", "", "")
    pg.city("6224", "Wanfercée-Baulet", "", "", "")
    pg.city("6230", "Buzet", "", "", "")
    pg.city("6230", "Obaix", "", "", "")
    pg.city("6230", "Pont-à-Celles", "", "", "")
    pg.city("6230", "Thiméon", "", "", "")
    pg.city("6230", "Viesville", "", "", "")
    pg.city("6238", "Liberchies", "", "", "")
    pg.city("6238", "Luttre", "", "", "")
    pg.city("6240", "Farciennes", "", "", "")
    pg.city("6240", "Pironchamps", "", "", "")
    pg.city("6250", "Aiseau", "", "", "")
    pg.city("6250", "Aiseau-Presles", "", "", "")
    pg.city("6250", "Pont-de-Loup", "", "", "")
    pg.city("6250", "Presles", "", "", "")
    pg.city("6250", "Roselies", "", "", "")
    pg.city("6280", "Acoz", "", "", "")
    pg.city("6280", "Gerpinnes", "", "", "")
    pg.city("6280", "Gougnies", "", "", "")
    pg.city("6280", "Joncret", "", "", "")
    pg.city("6280", "Loverval", "", "", "")
    pg.city("6280", "Villers-Poterie", "", "", "")
    pg.city("6440", "Boussu-lez-Walcourt", "", "", "")
    pg.city("6440", "Fourbechies", "", "", "")
    pg.city("6440", "Froidchapelle", "", "", "")
    pg.city("6440", "Vergnies", "", "", "")
    pg.city("6441", "Erpion", "", "", "")
    pg.city("6460", "Bailièvre", "", "", "")
    pg.city("6460", "Chimay", "", "", "")
    pg.city("6460", "Robechies", "", "", "")
    pg.city("6460", "Saint-Remy (Ht.)", "", "", "")
    pg.city("6460", "Salles", "", "", "")
    pg.city("6460", "Villers-la-Tour", "", "", "")
    pg.city("6461", "Virelles", "", "", "")
    pg.city("6462", "Vaulx-lez-Chimay", "", "", "")
    pg.city("6463", "Lompret", "", "", "")
    pg.city("6464", "Baileux", "", "", "")
    pg.city("6464", "Bourlers", "", "", "")
    pg.city("6464", "Forges", "", "", "")
    pg.city("6464", "L'Escaillère", "", "", "")
    pg.city("6464", "Rièzes", "", "", "")
    pg.city("6470", "Grandrieu", "", "", "")
    pg.city("6470", "Montbliart", "", "", "")
    pg.city("6470", "Rance", "", "", "")
    pg.city("6470", "Sautin", "", "", "")
    pg.city("6470", "Sivry", "", "", "")
    pg.city("6470", "Sivry-Rance", "", "", "")
    pg.city("6500", "Barbençon", "", "", "")
    pg.city("6500", "Beaumont", "", "", "")
    pg.city("6500", "Leugnies", "", "", "")
    pg.city("6500", "Leval-Chaudeville", "", "", "")
    pg.city("6500", "Renlies", "", "", "")
    pg.city("6500", "Solre-Saint-Géry", "", "", "")
    pg.city("6500", "Thirimont", "", "", "")
    pg.city("6511", "Strée (Ht.)", "", "", "")
    pg.city("6530", "Leers-et-Fosteau", "", "", "")
    pg.city("6530", "Thuin", "", "", "")
    pg.city("6531", "Biesme-sous-Thuin", "", "", "")
    pg.city("6532", "Ragnies", "", "", "")
    pg.city("6533", "Biercée", "", "", "")
    pg.city("6534", "Gozée", "", "", "")
    pg.city("6536", "Donstiennes", "", "", "")
    pg.city("6536", "Thuillies", "", "", "")
    pg.city("6540", "Lobbes", "", "", "")
    pg.city("6540", "Mont-Sainte-Geneviève", "", "", "")
    pg.city("6542", "Sars-la-Buissière", "", "", "")
    pg.city("6543", "Bienne-lez-Happart", "", "", "")
    pg.city("6560", "Bersillies-l'Abbaye", "", "", "")
    pg.city("6560", "Erquelinnes", "", "", "")
    pg.city("6560", "Grand-Reng", "", "", "")
    pg.city("6560", "Hantes-Wihéries", "", "", "")
    pg.city("6560", "Montignies-St-Christophe", "", "", "")
    pg.city("6560", "Solre-sur-Sambre", "", "", "")
    pg.city("6567", "Fontaine-Valmont", "", "", "")
    pg.city("6567", "Labuissière", "", "", "")
    pg.city("6567", "Merbes-le-Château", "", "", "")
    pg.city("6567", "Merbes-Sainte-Marie", "", "", "")
    pg.city("6590", "Momignies", "", "", "")
    pg.city("6591", "Macon", "", "", "")
    pg.city("6592", "Monceau-Imbrechies", "", "", "")
    pg.city("6593", "Macquenoise", "", "", "")
    pg.city("6594", "Beauwelz", "", "", "")
    pg.city("6596", "Forge-Philippe", "", "", "")
    pg.city("6596", "Seloignes", "", "", "")
    pg.city("6600", "Bastogne", "", "", "")
    pg.city("6600", "Longvilly", "", "", "")
    pg.city("6600", "Noville (Lux.)", "", "", "")
    pg.city("6600", "Villers-la-Bonne-Eau", "", "", "")
    pg.city("6600", "Wardin", "", "", "")
    pg.city("6630", "Martelange", "", "", "")
    pg.city("6637", "Fauvillers", "", "", "")
    pg.city("6637", "Hollange", "", "", "")
    pg.city("6637", "Tintange", "", "", "")
    pg.city("6640", "Hompré", "", "", "")
    pg.city("6640", "Morhet", "", "", "")
    pg.city("6640", "Nives", "", "", "")
    pg.city("6640", "Sibret", "", "", "")
    pg.city("6640", "Vaux-lez-Rosières", "", "", "")
    pg.city("6640", "Vaux-sur-Sûre", "", "", "")
    pg.city("6642", "Juseret", "", "", "")
    pg.city("6660", "Houffalize", "", "", "")
    pg.city("6660", "Nadrin", "", "", "")
    pg.city("6661", "Mont (Lux.)", "", "", "")
    pg.city("6661", "Tailles", "", "", "")
    pg.city("6662", "Tavigny", "", "", "")
    pg.city("6663", "Mabompré", "", "", "")
    pg.city("6666", "Wibrin", "", "", "")
    pg.city("6670", "Gouvy", "", "", "")
    pg.city("6670", "Limerlé", "", "", "")
    pg.city("6671", "Bovigny", "", "", "")
    pg.city("6672", "Beho", "", "", "")
    pg.city("6673", "Cherain", "", "", "")
    pg.city("6674", "Montleban", "", "", "")
    pg.city("6680", "Amberloup", "", "", "")
    pg.city("6680", "Sainte-Ode", "", "", "")
    pg.city("6680", "Tillet", "", "", "")
    pg.city("6681", "Lavacherie", "", "", "")
    pg.city("6686", "Flamierge", "", "", "")
    pg.city("6687", "Bertogne", "", "", "")
    pg.city("6688", "Longchamps (Lux.)", "", "", "")
    pg.city("6690", "Bihain", "", "", "")
    pg.city("6690", "Vielsalm", "", "", "")
    pg.city("6692", "Petit-Thier", "", "", "")
    pg.city("6698", "Grand-Halleux", "", "", "")
    
    

    pg.city("7000", "Mons", "Bergen", "Bergen", "Mons")
    pg.city("7011", "Ghlin", "", "", "")
    pg.city("7012", "Flénu", "", "", "")
    pg.city("7012", "Jemappes", "", "", "")
    pg.city("7020", "Casteau (Mons)", "", "", "")
    pg.city("7020", "Maisières", "", "", "")
    pg.city("7020", "Masnuy-Saint-Jean (Mons)", "", "", "")
    pg.city("7020", "Nimy (Mons)", "", "", "")
    pg.city("7021", "Havré", "", "", "")
    pg.city("7021", "Ville-sur-Haine (Mons)", "", "", "")
    pg.city("7022", "Harmignies", "", "", "")
    pg.city("7022", "Harveng", "", "", "")
    pg.city("7022", "Hyon", "", "", "")
    pg.city("7022", "Mesvin", "", "", "")
    pg.city("7022", "Nouvelles", "", "", "")
    pg.city("7024", "Ciply", "", "", "")
    pg.city("7030", "Saint-Symphorien", "", "", "")
    pg.city("7031", "Villers-Saint-Ghislain", "", "", "")
    pg.city("7032", "Spiennes", "", "", "")
    pg.city("7033", "Cuesmes", "", "", "")
    pg.city("7034", "Obourg", "", "", "")
    pg.city("7034", "Saint-Denis (Ht.)", "", "", "")
    pg.city("7040", "Asquillies", "", "", "")
    pg.city("7040", "Aulnois", "", "", "")
    pg.city("7040", "Blaregnies", "", "", "")
    pg.city("7040", "Bougnies", "", "", "")
    pg.city("7040", "Genly", "", "", "")
    pg.city("7040", "Goegnies-Chaussée", "", "", "")
    pg.city("7040", "Quévy-le-Grand", "", "", "")
    pg.city("7040", "Quévy-le-Petit", "", "", "")
    pg.city("7041", "Givry", "", "", "")
    pg.city("7041", "Havay", "", "", "")
    pg.city("7050", "Erbaut", "", "", "")
    pg.city("7050", "Erbisoeul", "", "", "")
    pg.city("7050", "Herchies", "", "", "")
    pg.city("7050", "Jurbise", "", "", "")
    pg.city("7050", "Masnuy-Saint-Pierre", "", "", "")
    pg.city("7050", "Masnuy-St-Jean (Jurbise)", "", "", "")
    pg.city("7060", "Horrues", "", "", "")
    pg.city("7060", "Soignies", "", "", "")
    pg.city("7061", "Thieusies", "", "", "")
    pg.city("7061", "Casteau (Soignies)", "", "", "")
    pg.city("7062", "Naast", "", "", "")
    pg.city("7063", "Ch.-Notre-Dame-Louvignies", "", "", "")
    pg.city("7063", "Neufvilles", "", "", "")
    pg.city("7070", "Gottignies", "", "", "")
    pg.city("7070", "Le Roeulx", "", "", "")
    pg.city("7070", "Mignault", "", "", "")
    pg.city("7070", "Thieu", "", "", "")
    pg.city("7070", "Ville-sur-Haine(Le Roeulx)", "", "", "")
    pg.city("7080", "Eugies (Frameries)", "", "", "")
    pg.city("7080", "Frameries", "", "", "")
    pg.city("7080", "La Bouverie", "", "", "")
    pg.city("7080", "Noirchain", "", "", "")
    pg.city("7080", "Sars-la-Bruyère", "", "", "")
    pg.city("7090", "Hennuyères", "", "", "")
    pg.city("7090", "Henripont", "", "", "")
    pg.city("7090", "Petit-Roeulx-lez-Braine", "", "", "")
    pg.city("7090", "Ronquières", "", "", "")
    pg.city("7090", "Steenkerque (Ht.)", "", "", "")
    pg.city("7090", "Braine-le-Comte", "'s-Gravenbrakel", "Braine-le-Comte", "Braine-le-Comte")
    pg.city("7100", "Haine-Saint-Paul", "", "", "")
    pg.city("7100", "Haine-Saint-Pierre", "", "", "")
    pg.city("7100", "La Louvière", "", "", "")
    pg.city("7100", "Saint-Vaast", "", "", "")
    pg.city("7100", "Trivières", "", "", "")
    pg.city("7110", "Boussoit", "", "", "")
    pg.city("7110", "Houdeng-Aimeries", "", "", "")
    pg.city("7110", "Houdeng-Goegnies", "", "", "")
    pg.city("7110", "Maurage", "", "", "")
    pg.city("7110", "Strépy-Bracquegnies", "", "", "")
    pg.city("7120", "Croix-lez-Rouveroy", "", "", "")
    pg.city("7120", "Estinnes", "", "", "")
    pg.city("7120", "Estinnes-au-Mont", "", "", "")
    pg.city("7120", "Estinnes-au-Val", "", "", "")
    pg.city("7120", "Fauroeulx", "", "", "")
    pg.city("7120", "Haulchin", "", "", "")
    pg.city("7120", "Peissant", "", "", "")
    pg.city("7120", "Rouveroy (Ht.)", "", "", "")
    pg.city("7120", "Vellereille-les-Brayeux", "", "", "")
    pg.city("7120", "Vellereille-le-Sec", "", "", "")
    pg.city("7130", "Battignies", "", "", "")
    pg.city("7130", "Binche", "", "", "")
    pg.city("7130", "Bray", "", "", "")
    pg.city("7131", "Waudrez", "", "", "")
    pg.city("7133", "Buvrinnes", "", "", "")
    pg.city("7134", "Epinois", "", "", "")
    pg.city("7134", "Leval-Trahegnies", "", "", "")
    pg.city("7134", "Péronnes-lez-Binche", "", "", "")
    pg.city("7134", "Ressaix", "", "", "")
    pg.city("7140", "Morlanwelz", "", "", "")
    pg.city("7140", "Morlanwelz-Mariemont", "", "", "")
    pg.city("7141", "Carnières", "", "", "")
    pg.city("7141", "Mont-Sainte-Aldegonde", "", "", "")
    pg.city("7160", "Chapelle-lez-Herlaimont", "", "", "")
    pg.city("7160", "Godarville", "", "", "")
    pg.city("7160", "Piéton", "", "", "")
    pg.city("7170", "Bellecourt", "", "", "")
    pg.city("7170", "Bois-d'Haine", "", "", "")
    pg.city("7170", "Fayt-lez-Manage", "", "", "")
    pg.city("7170", "La Hestre", "", "", "")
    pg.city("7170", "Manage", "", "", "")
    pg.city("7180", "Seneffe", "", "", "")
    pg.city("7181", "Arquennes", "", "", "")
    pg.city("7181", "Familleureux", "", "", "")
    pg.city("7181", "Feluy", "", "", "")
    pg.city("7181", "Petit-Roeulx-lez-Nivelles", "", "", "")
    pg.city("7190", "Ecaussinnes", "", "", "")
    pg.city("7190", "Ecaussinnes-d'Enghien", "", "", "")
    pg.city("7190", "Marche-lez-Ecaussinnes", "", "", "")
    pg.city("7191", "Ecaussinnes-Lalaing", "", "", "")
    pg.city("7300", "Boussu", "", "", "")
    pg.city("7301", "Hornu", "", "", "")
    pg.city("7320", "Bernissart", "", "", "")
    pg.city("7321", "Blaton", "", "", "")
    pg.city("7321", "Harchies", "", "", "")
    pg.city("7322", "Pommeroeul", "", "", "")
    pg.city("7322", "Ville-Pommeroeul", "", "", "")
    pg.city("7330", "Saint-Ghislain", "", "", "")
    pg.city("7331", "Baudour", "", "", "")
    pg.city("7332", "Neufmaison", "", "", "")
    pg.city("7332", "Sirault", "", "", "")
    pg.city("7333", "Tertre", "", "", "")
    pg.city("7334", "Hautrage", "", "", "")
    pg.city("7334", "Villerot", "", "", "")
    pg.city("7340", "Colfontaine", "", "", "")
    pg.city("7340", "Eugies (Colfontaine)", "", "", "")
    pg.city("7340", "Pâturages", "", "", "")
    pg.city("7340", "Warquignies", "", "", "")
    pg.city("7340", "Wasmes", "", "", "")
    pg.city("7350", "Hainin", "", "", "")
    pg.city("7350", "Hensies", "", "", "")
    pg.city("7350", "Montroeul-sur-Haine", "", "", "")
    pg.city("7350", "Thulin", "", "", "")
    pg.city("7370", "Blaugies", "", "", "")
    pg.city("7370", "Dour", "", "", "")
    pg.city("7370", "Elouges", "", "", "")
    pg.city("7370", "Wihéries", "", "", "")
    pg.city("7380", "Baisieux", "", "", "")
    pg.city("7380", "Quiévrain", "", "", "")
    pg.city("7382", "Audregnies", "", "", "")
    pg.city("7387", "Angre", "", "", "")
    pg.city("7387", "Angreau", "", "", "")
    pg.city("7387", "Athis", "", "", "")
    pg.city("7387", "Autreppe", "", "", "")
    pg.city("7387", "Erquennes", "", "", "")
    pg.city("7387", "Fayt-le-Franc", "", "", "")
    pg.city("7387", "Honnelles", "", "", "")
    pg.city("7387", "Marchipont", "", "", "")
    pg.city("7387", "Montignies-sur-Roc", "", "", "")
    pg.city("7387", "Onnezies", "", "", "")
    pg.city("7387", "Roisin", "", "", "")
    pg.city("7390", "Quaregnon", "", "", "")
    pg.city("7390", "Wasmuel", "", "", "")
    pg.city("7500", "Ere", "", "", "")
    pg.city("7500", "Saint-Maur", "", "", "")
    pg.city("7500", "Tournai", "", "", "")
    pg.city("7501", "Orcq", "", "", "")
    pg.city("7502", "Esplechin", "", "", "")
    pg.city("7503", "Froyennes", "", "", "")
    pg.city("7504", "Froidmont", "", "", "")
    pg.city("7506", "Willemeau", "", "", "")
    pg.city("7520", "Ramegnies-Chin", "", "", "")
    pg.city("7520", "Templeuve", "", "", "")
    pg.city("7521", "Chercq", "", "", "")
    pg.city("7522", "Blandain", "", "", "")
    pg.city("7522", "Hertain", "", "", "")
    pg.city("7522", "Lamain", "", "", "")
    pg.city("7522", "Marquain", "", "", "")
    pg.city("7530", "Gaurain-Ramecroix", "", "", "")
    pg.city("7531", "Havinnes", "", "", "")
    pg.city("7532", "Beclers", "", "", "")
    pg.city("7533", "Thimougies", "", "", "")
    pg.city("7534", "Barry", "", "", "")
    pg.city("7534", "Maulde", "", "", "")
    pg.city("7536", "Vaulx (Tournai)", "", "", "")
    pg.city("7538", "Vezon", "", "", "")
    pg.city("7540", "Kain (Tournai)", "", "", "")
    pg.city("7540", "Melles", "", "", "")
    pg.city("7540", "Quartes", "", "", "")
    pg.city("7540", "Rumillies", "", "", "")
    pg.city("7542", "Mont-Saint-Aubert", "", "", "")
    pg.city("7543", "Mourcourt", "", "", "")
    pg.city("7548", "Warchin", "", "", "")
    pg.city("7600", "Péruwelz", "", "", "")
    pg.city("7601", "Roucourt", "", "", "")
    pg.city("7602", "Bury", "", "", "")
    pg.city("7603", "Bon-Secours", "", "", "")
    pg.city("7604", "Baugnies", "", "", "")
    pg.city("7604", "Braffe", "", "", "")
    pg.city("7604", "Brasmenil", "", "", "")
    pg.city("7604", "Callenelle", "", "", "")
    pg.city("7604", "Wasmes-Audemez-Briffoeil", "", "", "")
    pg.city("7608", "Wiers", "", "", "")
    pg.city("7610", "Rumes", "", "", "")
    pg.city("7611", "La Glanerie", "", "", "")
    pg.city("7618", "Taintignies", "", "", "")
    pg.city("7620", "Bléharies", "", "", "")
    pg.city("7620", "Brunehaut", "", "", "")
    pg.city("7620", "Guignies", "", "", "")
    pg.city("7620", "Hollain", "", "", "")
    pg.city("7620", "Jollain-Merlin", "", "", "")
    pg.city("7620", "Wez-Velvain", "", "", "")
    pg.city("7621", "Lesdain", "", "", "")
    pg.city("7622", "Laplaigne", "", "", "")
    pg.city("7623", "Rongy", "", "", "")
    pg.city("7624", "Howardries", "", "", "")
    pg.city("7640", "Antoing", "", "", "")
    pg.city("7640", "Maubray", "", "", "")
    pg.city("7640", "Péronnes-lez-Antoing", "", "", "")
    pg.city("7641", "Bruyelle", "", "", "")
    pg.city("7642", "Calonne", "", "", "")
    pg.city("7643", "Fontenoy", "", "", "")
    pg.city("7700", "Luingne", "", "", "")
    pg.city("7700", "Mouscron", "", "", "")
    pg.city("7700", "Moucron", "Moeskroen", "Moucron", "Moucron")
    pg.city("7711", "Dottenijs", "", "", "")
    pg.city("7711", "Dottignies", "", "", "")
    pg.city("7712", "Herseaux", "", "", "")
    pg.city("7730", "Bailleul", "", "", "")
    pg.city("7730", "Estaimbourg", "", "", "")
    pg.city("7730", "Estaimpuis", "", "", "")
    pg.city("7730", "Evregnies", "", "", "")
    pg.city("7730", "Leers-Nord", "", "", "")
    pg.city("7730", "Néchin", "", "", "")
    pg.city("7730", "Saint-Léger (Ht.)", "", "", "")
    pg.city("7740", "Pecq", "", "", "")
    pg.city("7740", "Warcoing", "", "", "")
    pg.city("7742", "Hérinnes-lez-Pecq", "", "", "")
    pg.city("7743", "Esquelmes", "", "", "")
    pg.city("7743", "Obigies", "", "", "")
    pg.city("7750", "Amougies", "", "", "")
    pg.city("7750", "Anseroeul", "", "", "")
    pg.city("7750", "Mont-de-l'Enclus", "", "", "")
    pg.city("7750", "Orroir", "", "", "")
    pg.city("7750", "Russeignies", "", "", "")
    pg.city("7760", "Celles (Ht.)", "", "", "")
    pg.city("7760", "Escanaffles", "", "", "")
    pg.city("7760", "Molenbaix", "", "", "")
    pg.city("7760", "Popuelles", "", "", "")
    pg.city("7760", "Pottes", "", "", "")
    pg.city("7760", "Velaines", "", "", "")
    pg.city("7780", "Comines", "", "", "")
    pg.city("7780", "Komen", "", "", "")
    pg.city("7780", "Komen-Waasten", "", "", "")
    pg.city("7780", "Comines-Warneton", "Komen-Waasten", "Comines-Warneton", "Comines-Warneton")
    pg.city("7781", "Houthem (Comines)", "", "", "")
    pg.city("7782", "Ploegsteert", "", "", "")
    pg.city("7783", "Bizet", "", "", "")
    pg.city("7784", "Bas-Warneton", "", "", "")
    pg.city("7784", "Neerwaasten", "", "", "")
    pg.city("7784", "Waasten", "", "", "")
    pg.city("7784", "Warneton", "", "", "")
    pg.city("7800", "Ath", "", "", "")
    pg.city("7800", "Lanquesaint", "", "", "")
    pg.city("7801", "Irchonwelz", "", "", "")
    pg.city("7802", "Ormeignies", "", "", "")
    pg.city("7803", "Bouvignies", "", "", "")
    pg.city("7804", "Ostiches", "", "", "")
    pg.city("7804", "Rebaix", "", "", "")
    pg.city("7810", "Maffle", "", "", "")
    pg.city("7811", "Arbre (Ht.)", "", "", "")
    pg.city("7812", "Houtaing", "", "", "")
    pg.city("7812", "Ligne", "", "", "")
    pg.city("7812", "Mainvault", "", "", "")
    pg.city("7812", "Moulbaix", "", "", "")
    pg.city("7812", "Villers-Notre-Dame", "", "", "")
    pg.city("7812", "Villers-Saint-Amand", "", "", "")
    pg.city("7822", "Ghislenghien", "", "", "")
    pg.city("7822", "Isières", "", "", "")
    pg.city("7822", "Meslin-l'Evêque", "", "", "")
    pg.city("7823", "Gibecq", "", "", "")
    pg.city("7830", "Bassilly", "", "", "")
    pg.city("7830", "Fouleng", "", "", "")
    pg.city("7830", "Gondregnies", "", "", "")
    pg.city("7830", "Graty", "", "", "")
    pg.city("7830", "Hellebecq", "", "", "")
    pg.city("7830", "Hoves (Ht.)", "", "", "")
    pg.city("7830", "Silly", "", "", "")
    pg.city("7830", "Thoricourt", "", "", "")
    pg.city("7850", "Lettelingen", "", "", "")
    pg.city("7850", "Marcq", "", "", "")
    pg.city("7850", "Mark", "", "", "")
    pg.city("7850", "Petit-Enghien", "", "", "")
    pg.city("7850", "Enghien", "Edingen", "Enghien", "Enghien")
    pg.city("7860", "Lessines", "Lessen", "Lessines", "Lessines")
    pg.city("7861", "Papignies", "", "", "")
    pg.city("7861", "Wannebecq", "", "", "")
    pg.city("7862", "Ogy", "", "", "")
    pg.city("7863", "Ghoy", "", "", "")
    pg.city("7864", "Deux-Acren", "", "", "")
    pg.city("7866", "Bois-de-Lessines", "", "", "")
    pg.city("7866", "Ollignies", "", "", "")
    pg.city("7870", "Bauffe", "", "", "")
    pg.city("7870", "Cambron-Saint-Vincent", "", "", "")
    pg.city("7870", "Lens", "", "", "")
    pg.city("7870", "Lombise", "", "", "")
    pg.city("7870", "Montignies-lez-Lens", "", "", "")
    pg.city("7880", "Flobecq", "", "", "")
    pg.city("7880", "Vloesberg", "", "", "")
    pg.city("7890", "Ellezelles", "", "", "")
    pg.city("7890", "Lahamaide", "", "", "")
    pg.city("7890", "Wodecq", "", "", "")
    pg.city("7900", "Grandmetz", "", "", "")
    pg.city("7900", "Leuze-en-Hainaut", "", "", "")
    pg.city("7901", "Thieulain", "", "", "")
    pg.city("7903", "Blicquy", "", "", "")
    pg.city("7903", "Chapelle-à-Oie", "", "", "")
    pg.city("7903", "Chapelle-à-Wattines", "", "", "")
    pg.city("7904", "Pipaix", "", "", "")
    pg.city("7904", "Tourpes", "", "", "")
    pg.city("7904", "Willaupuis", "", "", "")
    pg.city("7906", "Gallaix", "", "", "")
    pg.city("7910", "Anvaing", "", "", "")
    pg.city("7910", "Arc-Ainières", "", "", "")
    pg.city("7910", "Arc-Wattripont", "", "", "")
    pg.city("7910", "Cordes", "", "", "")
    pg.city("7910", "Ellignies-lez-Frasnes", "", "", "")
    pg.city("7910", "Forest (Ht.)", "", "", "")
    pg.city("7910", "Wattripont", "", "", "")
    pg.city("7911", "Buissenal", "", "", "")
    pg.city("7911", "Frasnes-lez-Buissenal", "", "", "")
    pg.city("7911", "Hacquegnies", "", "", "")
    pg.city("7911", "Herquegies", "", "", "")
    pg.city("7911", "Montroeul-au-Bois", "", "", "")
    pg.city("7911", "Moustier (Ht.)", "", "", "")
    pg.city("7911", "Oeudeghien", "", "", "")
    pg.city("7912", "Dergneau", "", "", "")
    pg.city("7912", "Saint-Sauveur", "", "", "")
    pg.city("7940", "Brugelette", "", "", "")
    pg.city("7940", "Cambron-Casteau", "", "", "")
    pg.city("7941", "Attre", "", "", "")
    pg.city("7942", "Mévergnies-lez-Lens", "", "", "")
    pg.city("7943", "Gages", "", "", "")
    pg.city("7950", "Chièvres", "", "", "")
    pg.city("7950", "Grosage", "", "", "")
    pg.city("7950", "Huissignies", "", "", "")
    pg.city("7950", "Ladeuze", "", "", "")
    pg.city("7950", "Tongre-Saint-Martin", "", "", "")
    pg.city("7951", "Tongre-Notre-Dame", "", "", "")
    pg.city("7970", "Beloeil", "", "", "")
    pg.city("7971", "Basècles", "", "", "")
    pg.city("7971", "Ramegnies", "", "", "")
    pg.city("7971", "Thumaide", "", "", "")
    pg.city("7971", "Wadelincourt", "", "", "")
    pg.city("7972", "Aubechies", "", "", "")
    pg.city("7972", "Ellignies-Sainte-Anne", "", "", "")
    pg.city("7972", "Quevaucamps", "", "", "")
    pg.city("7973", "Grandglise", "", "", "")
    pg.city("7973", "Stambruges", "", "", "")
