# -*- coding: UTF-8 -*-
# Copyright 2014 Luc Saffre
# This file is part of the commondata library.
# The commondata library is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
# The commondata library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with the commondata library; if not, see
# <http://www.gnu.org/licenses/>.


from __future__ import unicode_literals


def populate(pg):

    pg.set_args('fr nl de en')
    pg.province("Luxembourg", "Luxemburg", "Luxemburg", "Luxembourg")
    pg.set_args('zip_code fr nl de en')

    pg.city("6700", "Arlon", "", "", "")
    pg.city("6700", "Bonnert", "", "", "")
    pg.city("6700", "Heinsch", "", "", "")
    pg.city("6700", "Toernich", "", "", "")
    pg.city("6704", "Guirsch", "", "", "")
    pg.city("6706", "Autelbas", "", "", "")
    pg.city("6717", "Attert", "", "", "")
    pg.city("6717", "Nobressart", "", "", "")
    pg.city("6717", "Nothomb", "", "", "")
    pg.city("6717", "Thiaumont", "", "", "")
    pg.city("6717", "Tontelange", "", "", "")
    pg.city("6720", "Habay", "", "", "")
    pg.city("6720", "Habay-la-Neuve", "", "", "")
    pg.city("6720", "Hachy", "", "", "")
    pg.city("6721", "Anlier", "", "", "")
    pg.city("6723", "Habay-la-Vieille", "", "", "")
    pg.city("6724", "Houdemont", "", "", "")
    pg.city("6724", "Rulles", "", "", "")
    pg.city("6730", "Bellefontaine (Lux.)", "", "", "")
    pg.city("6730", "Rossignol", "", "", "")
    pg.city("6730", "Saint-Vincent", "", "", "")
    pg.city("6730", "Tintigny", "", "", "")
    pg.city("6740", "Etalle", "", "", "")
    pg.city("6740", "Sainte-Marie-sur-Semois", "", "", "")
    pg.city("6740", "Villers-sur-Semois", "", "", "")
    pg.city("6741", "Vance", "", "", "")
    pg.city("6742", "Chantemelle", "", "", "")
    pg.city("6743", "Buzenol", "", "", "")
    pg.city("6747", "Châtillon", "", "", "")
    pg.city("6747", "Meix-le-Tige", "", "", "")
    pg.city("6747", "Saint-Léger (Lux.)", "", "", "")
    pg.city("6750", "Musson", "", "", "")
    pg.city("6750", "Mussy-la-Ville", "", "", "")
    pg.city("6750", "Signeulx", "", "", "")
    pg.city("6760", "Bleid", "", "", "")
    pg.city("6760", "Ethe", "", "", "")
    pg.city("6760", "Ruette", "", "", "")
    pg.city("6760", "Virton", "", "", "")
    pg.city("6761", "Latour", "", "", "")
    pg.city("6762", "Saint-Mard", "", "", "")
    pg.city("6767", "Dampicourt", "", "", "")
    pg.city("6767", "Harnoncourt", "", "", "")
    pg.city("6767", "Lamorteau", "", "", "")
    pg.city("6767", "Rouvroy", "", "", "")
    pg.city("6767", "Torgny", "", "", "")
    pg.city("6769", "Gérouville", "", "", "")
    pg.city("6769", "Meix-devant-Virton", "", "", "")
    pg.city("6769", "Robelmont", "", "", "")
    pg.city("6769", "Sommethonne", "", "", "")
    pg.city("6769", "Villers-la-Loue", "", "", "")
    pg.city("6780", "Hondelange", "", "", "")
    pg.city("6780", "Messancy", "", "", "")
    pg.city("6780", "Wolkrange", "", "", "")
    pg.city("6781", "Sélange", "", "", "")
    pg.city("6782", "Habergy", "", "", "")
    pg.city("6790", "Aubange", "", "", "")
    pg.city("6791", "Athus", "", "", "")
    pg.city("6792", "Halanzy", "", "", "")
    pg.city("6792", "Rachecourt", "", "", "")
    

    pg.city("6800", "Bras", "", "", "")
    pg.city("6800", "Freux", "", "", "")
    pg.city("6800", "Libramont-Chevigny", "", "", "")
    pg.city("6800", "Moircy", "", "", "")
    pg.city("6800", "Recogne", "", "", "")
    pg.city("6800", "Remagne", "", "", "")
    pg.city("6800", "Sainte-Marie-Chevigny", "", "", "")
    pg.city("6800", "Saint-Pierre", "", "", "")
    pg.city("6810", "Chiny", "", "", "")
    pg.city("6810", "Izel", "", "", "")
    pg.city("6810", "Jamoigne", "", "", "")
    pg.city("6811", "Les Bulles", "", "", "")
    pg.city("6812", "Suxy", "", "", "")
    pg.city("6813", "Termes", "", "", "")
    pg.city("6820", "Florenville", "", "", "")
    pg.city("6820", "Fontenoille", "", "", "")
    pg.city("6820", "Muno", "", "", "")
    pg.city("6820", "Sainte-Cécile", "", "", "")
    pg.city("6821", "Lacuisine", "", "", "")
    pg.city("6823", "Villers-devant-Orval", "", "", "")
    pg.city("6824", "Chassepierre", "", "", "")
    pg.city("6830", "Bouillon", "", "", "")
    pg.city("6830", "Les Hayons", "", "", "")
    pg.city("6830", "Poupehan", "", "", "")
    pg.city("6830", "Rochehaut", "", "", "")
    pg.city("6831", "Noirefontaine", "", "", "")
    pg.city("6832", "Sensenruth", "", "", "")
    pg.city("6833", "Ucimont", "", "", "")
    pg.city("6833", "Vivy", "", "", "")
    pg.city("6834", "Bellevaux", "", "", "")
    pg.city("6836", "Dohan", "", "", "")
    pg.city("6838", "Corbion", "", "", "")
    pg.city("6840", "Grandvoir", "", "", "")
    pg.city("6840", "Grapfontaine", "", "", "")
    pg.city("6840", "Hamipré", "", "", "")
    pg.city("6840", "Longlier", "", "", "")
    pg.city("6840", "Neufchâteau", "", "", "")
    pg.city("6840", "Tournay", "", "", "")
    pg.city("6850", "Carlsbourg", "", "", "")
    pg.city("6850", "Offagne", "", "", "")
    pg.city("6850", "Paliseul", "", "", "")
    pg.city("6851", "Nollevaux", "", "", "")
    pg.city("6852", "Maissin", "", "", "")
    pg.city("6852", "Opont", "", "", "")
    pg.city("6853", "Framont", "", "", "")
    pg.city("6856", "Fays-les-Veneurs", "", "", "")
    pg.city("6860", "Assenois", "", "", "")
    pg.city("6860", "Ebly", "", "", "")
    pg.city("6860", "Léglise", "", "", "")
    pg.city("6860", "Mellier", "", "", "")
    pg.city("6860", "Witry", "", "", "")
    pg.city("6870", "Arville", "", "", "")
    pg.city("6870", "Awenne", "", "", "")
    pg.city("6870", "Hatrival", "", "", "")
    pg.city("6870", "Mirwart", "", "", "")
    pg.city("6870", "Saint-Hubert", "", "", "")
    pg.city("6870", "Vesqueville", "", "", "")
    pg.city("6880", "Auby-sur-Semois", "", "", "")
    pg.city("6880", "Bertrix", "", "", "")
    pg.city("6880", "Cugnon", "", "", "")
    pg.city("6880", "Jehonville", "", "", "")
    pg.city("6880", "Orgeo", "", "", "")
    pg.city("6887", "Herbeumont", "", "", "")
    pg.city("6887", "Saint-Médard", "", "", "")
    pg.city("6887", "Straimont", "", "", "")
    pg.city("6890", "Anloy", "", "", "")
    pg.city("6890", "Libin", "", "", "")
    pg.city("6890", "Ochamps", "", "", "")
    pg.city("6890", "Redu", "", "", "")
    pg.city("6890", "Smuid", "", "", "")
    pg.city("6890", "Transinne", "", "", "")
    pg.city("6890", "Villance", "", "", "")
    pg.city("6900", "Aye", "", "", "")
    pg.city("6900", "Hargimont", "", "", "")
    pg.city("6900", "Humain", "", "", "")
    pg.city("6900", "Marche-en-Famenne", "", "", "")
    pg.city("6900", "On", "", "", "")
    pg.city("6900", "Roy", "", "", "")
    pg.city("6900", "Waha", "", "", "")
    pg.city("6920", "Sohier", "", "", "")
    pg.city("6920", "Wellin", "", "", "")
    pg.city("6921", "Chanly", "", "", "")
    pg.city("6922", "Halma", "", "", "")
    pg.city("6924", "Lomprez", "", "", "")
    pg.city("6927", "Bure", "", "", "")
    pg.city("6927", "Grupont", "", "", "")
    pg.city("6927", "Resteigne", "", "", "")
    pg.city("6927", "Tellin", "", "", "")
    pg.city("6929", "Daverdisse", "", "", "")
    pg.city("6929", "Gembes", "", "", "")
    pg.city("6929", "Haut-Fays", "", "", "")
    pg.city("6929", "Porcheresse (Lux.)", "", "", "")
    pg.city("6940", "Barvaux-sur-Ourthe", "", "", "")
    pg.city("6940", "Durbuy", "", "", "")
    pg.city("6940", "Grandhan", "", "", "")
    pg.city("6940", "Septon", "", "", "")
    pg.city("6940", "Wéris", "", "", "")
    pg.city("6941", "Bende", "", "", "")
    pg.city("6941", "Bomal-sur-Ourthe", "", "", "")
    pg.city("6941", "Borlon", "", "", "")
    pg.city("6941", "Heyd", "", "", "")
    pg.city("6941", "Izier", "", "", "")
    pg.city("6941", "Tohogne", "", "", "")
    pg.city("6941", "Villers-Sainte-Gertrude", "", "", "")
    pg.city("6950", "Harsin", "", "", "")
    pg.city("6950", "Nassogne", "", "", "")
    pg.city("6951", "Bande", "", "", "")
    pg.city("6952", "Grune", "", "", "")
    pg.city("6953", "Ambly", "", "", "")
    pg.city("6953", "Forrières", "", "", "")
    pg.city("6953", "Lesterny", "", "", "")
    pg.city("6953", "Masbourg", "", "", "")
    pg.city("6960", "Dochamps", "", "", "")
    pg.city("6960", "Grandmenil", "", "", "")
    pg.city("6960", "Harre", "", "", "")
    pg.city("6960", "Malempré", "", "", "")
    pg.city("6960", "Manhay", "", "", "")
    pg.city("6960", "Odeigne", "", "", "")
    pg.city("6960", "Vaux-Chavanne", "", "", "")
    pg.city("6970", "Tenneville", "", "", "")
    pg.city("6971", "Champlon", "", "", "")
    pg.city("6972", "Erneuville", "", "", "")
    pg.city("6980", "Beausaint", "", "", "")
    pg.city("6980", "La Roche-en-Ardenne", "", "", "")
    pg.city("6982", "Samrée", "", "", "")
    pg.city("6983", "Ortho", "", "", "")
    pg.city("6984", "Hives", "", "", "")
    pg.city("6986", "Halleux", "", "", "")
    pg.city("6987", "Beffe", "", "", "")
    pg.city("6987", "Hodister", "", "", "")
    pg.city("6987", "Marcourt", "", "", "")
    pg.city("6987", "Rendeux", "", "", "")
    pg.city("6990", "Fronville", "", "", "")
    pg.city("6990", "Hampteau", "", "", "")
    pg.city("6990", "Hotton", "", "", "")
    pg.city("6990", "Marenne", "", "", "")
    pg.city("6997", "Amonines", "", "", "")
    pg.city("6997", "Erezée", "", "", "")
    pg.city("6997", "Mormont", "", "", "")
    pg.city("6997", "Soy", "", "", "")
