# -*- coding: UTF-8 -*-
# Copyright 2014 Luc Saffre
# This file is part of the commondata library.
# The commondata library is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
# The commondata library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with the commondata library; if not, see
# <http://www.gnu.org/licenses/>.


from __future__ import unicode_literals


def populate(pg):

    pg.set_args('fr nl de en')
    pg.province("Namur", "Namen", "Namür", "Namur")
    pg.set_args('zip_code fr nl de en')

    pg.city("5000", "Namur", "Namen", "Namür", "Namur")
    pg.city("5000", "Beez", "", "", "")
    pg.city("5001", "Belgrade", "", "", "")
    pg.city("5002", "Saint-Servais", "", "", "")
    pg.city("5003", "Saint-Marc", "", "", "")
    pg.city("5004", "Bouge", "", "", "")
    pg.city("5020", "Champion", "", "", "")
    pg.city("5020", "Daussoulx", "", "", "")
    pg.city("5020", "Flawinne", "", "", "")
    pg.city("5020", "Malonne", "", "", "")
    pg.city("5020", "Suarlée", "", "", "")
    pg.city("5020", "Temploux", "", "", "")
    pg.city("5020", "Vedrin", "", "", "")
    pg.city("5021", "Boninne", "", "", "")
    pg.city("5022", "Cognelée", "", "", "")
    pg.city("5024", "Gelbressée", "", "", "")
    pg.city("5024", "Marche-les-Dames", "", "", "")
    pg.city("5030", "Beuzet", "", "", "")
    pg.city("5030", "Ernage", "", "", "")
    pg.city("5030", "Gembloux", "", "", "")
    pg.city("5030", "Grand-Manil", "", "", "")
    pg.city("5030", "Lonzée", "", "", "")
    pg.city("5030", "Sauvenière", "", "", "")
    pg.city("5031", "Grand-Leez", "", "", "")
    pg.city("5032", "Bossière", "", "", "")
    pg.city("5032", "Bothey", "", "", "")
    pg.city("5032", "Corroy-le-Château", "", "", "")
    pg.city("5032", "Isnes", "", "", "")
    pg.city("5032", "Mazy", "", "", "")
    pg.city("5060", "Arsimont", "", "", "")
    pg.city("5060", "Auvelais", "", "", "")
    pg.city("5060", "Falisolle", "", "", "")
    pg.city("5060", "Keumiée", "", "", "")
    pg.city("5060", "Moignelée", "", "", "")
    pg.city("5060", "Sambreville", "", "", "")
    pg.city("5060", "Tamines", "", "", "")
    pg.city("5060", "Velaine-sur-Sambre", "", "", "")
    pg.city("5070", "Aisemont", "", "", "")
    pg.city("5070", "Fosses-la-Ville", "", "", "")
    pg.city("5070", "Le Roux", "", "", "")
    pg.city("5070", "Sart-Eustache", "", "", "")
    pg.city("5070", "Sart-Saint-Laurent", "", "", "")
    pg.city("5070", "Vitrival", "", "", "")
    pg.city("5080", "Emines", "", "", "")
    pg.city("5080", "Rhisnes", "", "", "")
    pg.city("5080", "Villers-lez-Heest", "", "", "")
    pg.city("5080", "Warisoulx", "", "", "")
    pg.city("5081", "Bovesse", "", "", "")
    pg.city("5081", "Meux", "", "", "")
    pg.city("5081", "Saint-Denis-Bovesse", "", "", "")
    pg.city("5100", "Dave", "", "", "")
    pg.city("5100", "Jambes (Namur)", "", "", "")
    pg.city("5100", "Naninne", "", "", "")
    pg.city("5100", "Wépion", "", "", "")
    pg.city("5100", "Wierde", "", "", "")
    pg.city("5101", "Erpent", "", "", "")
    pg.city("5101", "Lives-sur-Meuse", "", "", "")
    pg.city("5101", "Loyers", "", "", "")
    pg.city("5140", "Boignée", "", "", "")
    pg.city("5140", "Ligny", "", "", "")
    pg.city("5140", "Sombreffe", "", "", "")
    pg.city("5140", "Tongrinne", "", "", "")
    pg.city("5150", "Floreffe", "", "", "")
    pg.city("5150", "Floriffoux", "", "", "")
    pg.city("5150", "Franière", "", "", "")
    pg.city("5150", "Soye (Nam.)", "", "", "")
    pg.city("5170", "Arbre (Nam.)", "", "", "")
    pg.city("5170", "Bois-de-Villers", "", "", "")
    pg.city("5170", "Lesve", "", "", "")
    pg.city("5170", "Lustin", "", "", "")
    pg.city("5170", "Profondeville", "", "", "")
    pg.city("5170", "Rivière", "", "", "")
    pg.city("5190", "Balâtre", "", "", "")
    pg.city("5190", "Ham-sur-Sambre", "", "", "")
    pg.city("5190", "Jemeppe-sur-Sambre", "", "", "")
    pg.city("5190", "Mornimont", "", "", "")
    pg.city("5190", "Moustier-sur-Sambre", "", "", "")
    pg.city("5190", "Onoz", "", "", "")
    pg.city("5190", "Saint-Martin", "", "", "")
    pg.city("5190", "Spy", "", "", "")
    pg.city("5300", "Andenne", "", "", "")
    pg.city("5300", "Bonneville", "", "", "")
    pg.city("5300", "Coutisse", "", "", "")
    pg.city("5300", "Landenne", "", "", "")
    pg.city("5300", "Maizeret", "", "", "")
    pg.city("5300", "Namêche", "", "", "")
    pg.city("5300", "Sclayn", "", "", "")
    pg.city("5300", "Seilles", "", "", "")
    pg.city("5300", "Thon", "", "", "")
    pg.city("5300", "Vezin", "", "", "")
    pg.city("5310", "Aische-en-Refail", "", "", "")
    pg.city("5310", "Bolinne", "", "", "")
    pg.city("5310", "Boneffe", "", "", "")
    pg.city("5310", "Branchon", "", "", "")
    pg.city("5310", "Dhuy", "", "", "")
    pg.city("5310", "Eghezée", "", "", "")
    pg.city("5310", "Hanret", "", "", "")
    pg.city("5310", "Leuze (Nam.)", "", "", "")
    pg.city("5310", "Liernu", "", "", "")
    pg.city("5310", "Longchamps (Nam.)", "", "", "")
    pg.city("5310", "Mehaigne", "", "", "")
    pg.city("5310", "Noville-sur-Méhaigne", "", "", "")
    pg.city("5310", "Saint-Germain", "", "", "")
    pg.city("5310", "Taviers (Nam.)", "", "", "")
    pg.city("5310", "Upigny", "", "", "")
    pg.city("5310", "Waret-la-Chaussée", "", "", "")
    pg.city("5330", "Assesse", "", "", "")
    pg.city("5330", "Maillen", "", "", "")
    pg.city("5330", "Sart-Bernard", "", "", "")
    pg.city("5332", "Crupet", "", "", "")
    pg.city("5333", "Sorinne-la-Longue", "", "", "")
    pg.city("5334", "Florée", "", "", "")
    pg.city("5336", "Courrière", "", "", "")
    pg.city("5340", "Faulx-les-Tombes", "", "", "")
    pg.city("5340", "Gesves", "", "", "")
    pg.city("5340", "Haltinne", "", "", "")
    pg.city("5340", "Mozet", "", "", "")
    pg.city("5340", "Sorée", "", "", "")
    pg.city("5350", "Evelette", "", "", "")
    pg.city("5350", "Ohey", "", "", "")
    pg.city("5351", "Haillot", "", "", "")
    pg.city("5352", "Perwez-Haillot", "", "", "")
    pg.city("5353", "Goesnes", "", "", "")
    pg.city("5354", "Jallet", "", "", "")
    pg.city("5360", "Hamois", "", "", "")
    pg.city("5360", "Natoye", "", "", "")
    pg.city("5361", "Mohiville", "", "", "")
    pg.city("5361", "Scy", "", "", "")
    pg.city("5362", "Achet", "", "", "")
    pg.city("5363", "Emptinne", "", "", "")
    pg.city("5364", "Schaltin", "", "", "")
    pg.city("5370", "Barvaux-Condroz", "", "", "")
    pg.city("5370", "Flostoy", "", "", "")
    pg.city("5370", "Havelange", "", "", "")
    pg.city("5370", "Jeneffe (Nam.)", "", "", "")
    pg.city("5370", "Porcheresse (Nam.)", "", "", "")
    pg.city("5370", "Verlée", "", "", "")
    pg.city("5372", "Méan", "", "", "")
    pg.city("5374", "Maffe", "", "", "")
    pg.city("5376", "Miécret", "", "", "")
    pg.city("5377", "Baillonville", "", "", "")
    pg.city("5377", "Bonsin", "", "", "")
    pg.city("5377", "Heure (Nam.)", "", "", "")
    pg.city("5377", "Hogne", "", "", "")
    pg.city("5377", "Nettinne", "", "", "")
    pg.city("5377", "Noiseux", "", "", "")
    pg.city("5377", "Sinsin", "", "", "")
    pg.city("5377", "Somme-Leuze", "", "", "")
    pg.city("5377", "Waillet", "", "", "")
    pg.city("5380", "Bierwart", "", "", "")
    pg.city("5380", "Cortil-Wodon", "", "", "")
    pg.city("5380", "Fernelmont", "", "", "")
    pg.city("5380", "Forville", "", "", "")
    pg.city("5380", "Franc-Waret", "", "", "")
    pg.city("5380", "Hemptinne (Fernelmont)", "", "", "")
    pg.city("5380", "Hingeon", "", "", "")
    pg.city("5380", "Marchovelette", "", "", "")
    pg.city("5380", "Noville-les-Bois", "", "", "")
    pg.city("5380", "Pontillas", "", "", "")
    pg.city("5380", "Tillier", "", "", "")
    pg.city("5500", "Anseremme", "", "", "")
    pg.city("5500", "Bouvignes-sur-Meuse", "", "", "")
    pg.city("5500", "Dinant", "", "", "")
    pg.city("5500", "Dréhance", "", "", "")
    pg.city("5500", "Falmagne", "", "", "")
    pg.city("5500", "Falmignoul", "", "", "")
    pg.city("5500", "Furfooz", "", "", "")
    pg.city("5501", "Lisogne", "", "", "")
    pg.city("5502", "Thynes", "", "", "")
    pg.city("5503", "Sorinnes", "", "", "")
    pg.city("5504", "Foy-Notre-Dame", "", "", "")
    pg.city("5520", "Anthée", "", "", "")
    pg.city("5520", "Onhaye", "", "", "")
    pg.city("5521", "Serville", "", "", "")
    pg.city("5522", "Falaën", "", "", "")
    pg.city("5523", "Sommière", "", "", "")
    pg.city("5523", "Weillen", "", "", "")
    pg.city("5524", "Gerin", "", "", "")
    pg.city("5530", "Dorinne", "", "", "")
    pg.city("5530", "Durnal", "", "", "")
    pg.city("5530", "Evrehailles", "", "", "")
    pg.city("5530", "Godinne", "", "", "")
    pg.city("5530", "Houx", "", "", "")
    pg.city("5530", "Mont (Nam.)", "", "", "")
    pg.city("5530", "Purnode", "", "", "")
    pg.city("5530", "Spontin", "", "", "")
    pg.city("5530", "Yvoir", "", "", "")
    pg.city("5537", "Anhée", "", "", "")
    pg.city("5537", "Annevoie-Rouillon", "", "", "")
    pg.city("5537", "Bioul", "", "", "")
    pg.city("5537", "Denée", "", "", "")
    pg.city("5537", "Haut-le-Wastia", "", "", "")
    pg.city("5537", "Sosoye", "", "", "")
    pg.city("5537", "Warnant", "", "", "")
    pg.city("5540", "Hastière", "", "", "")
    pg.city("5540", "Hastière-Lavaux", "", "", "")
    pg.city("5540", "Hermeton-sur-Meuse", "", "", "")
    pg.city("5540", "Waulsort", "", "", "")
    pg.city("5541", "Hastière-par-Delà", "", "", "")
    pg.city("5542", "Blaimont", "", "", "")
    pg.city("5543", "Heer", "", "", "")
    pg.city("5544", "Agimont", "", "", "")
    pg.city("5550", "Alle", "", "", "")
    pg.city("5550", "Bagimont", "", "", "")
    pg.city("5550", "Bohan", "", "", "")
    pg.city("5550", "Chairière", "", "", "")
    pg.city("5550", "Laforêt", "", "", "")
    pg.city("5550", "Membre", "", "", "")
    pg.city("5550", "Mouzaive", "", "", "")
    pg.city("5550", "Nafraiture", "", "", "")
    pg.city("5550", "Orchimont", "", "", "")
    pg.city("5550", "Pussemange", "", "", "")
    pg.city("5550", "Sugny", "", "", "")
    pg.city("5550", "Vresse-sur-Semois", "", "", "")
    pg.city("5555", "Baillamont", "", "", "")
    pg.city("5555", "Bellefontaine (Nam.)", "", "", "")
    pg.city("5555", "Bièvre", "", "", "")
    pg.city("5555", "Cornimont", "", "", "")
    pg.city("5555", "Graide", "", "", "")
    pg.city("5555", "Gros-Fays", "", "", "")
    pg.city("5555", "Monceau-en-Ardenne", "", "", "")
    pg.city("5555", "Naomé", "", "", "")
    pg.city("5555", "Oizy", "", "", "")
    pg.city("5555", "Petit-Fays", "", "", "")
    pg.city("5560", "Ciergnon", "", "", "")
    pg.city("5560", "Finnevaux", "", "", "")
    pg.city("5560", "Houyet", "", "", "")
    pg.city("5560", "Hulsonniaux", "", "", "")
    pg.city("5560", "Mesnil-Eglise", "", "", "")
    pg.city("5560", "Mesnil-Saint-Blaise", "", "", "")
    pg.city("5561", "Celles (Nam.)", "", "", "")
    pg.city("5562", "Custinne", "", "", "")
    pg.city("5563", "Hour", "", "", "")
    pg.city("5564", "Wanlin", "", "", "")
    pg.city("5570", "Baronville", "", "", "")
    pg.city("5570", "Beauraing", "", "", "")
    pg.city("5570", "Dion", "", "", "")
    pg.city("5570", "Felenne", "", "", "")
    pg.city("5570", "Feschaux", "", "", "")
    pg.city("5570", "Honnay", "", "", "")
    pg.city("5570", "Javingue", "", "", "")
    pg.city("5570", "Vonêche", "", "", "")
    pg.city("5570", "Wancennes", "", "", "")
    pg.city("5570", "Winenne", "", "", "")
    pg.city("5571", "Wiesme", "", "", "")
    pg.city("5572", "Focant", "", "", "")
    pg.city("5573", "Martouzin-Neuville", "", "", "")
    pg.city("5574", "Pondrôme", "", "", "")
    pg.city("5575", "Bourseigne-Neuve", "", "", "")
    pg.city("5575", "Bourseigne-Vieille", "", "", "")
    pg.city("5575", "Gedinne", "", "", "")
    pg.city("5575", "Houdremont", "", "", "")
    pg.city("5575", "Louette-Saint-Denis", "", "", "")
    pg.city("5575", "Louette-Saint-Pierre", "", "", "")
    pg.city("5575", "Malvoisin", "", "", "")
    pg.city("5575", "Patignies", "", "", "")
    pg.city("5575", "Rienne", "", "", "")
    pg.city("5575", "Sart-Custinne", "", "", "")
    pg.city("5575", "Vencimont", "", "", "")
    pg.city("5575", "Willerzie", "", "", "")
    pg.city("5576", "Froidfontaine", "", "", "")
    pg.city("5580", "Ave-et-Auffe", "", "", "")
    pg.city("5580", "Buissonville", "", "", "")
    pg.city("5580", "Eprave", "", "", "")
    pg.city("5580", "Han-sur-Lesse", "", "", "")
    pg.city("5580", "Jemelle", "", "", "")
    pg.city("5580", "Lavaux-Sainte-Anne", "", "", "")
    pg.city("5580", "Lessive", "", "", "")
    pg.city("5580", "Mont-Gauthier", "", "", "")
    pg.city("5580", "Rochefort", "", "", "")
    pg.city("5580", "Villers-sur-Lesse", "", "", "")
    pg.city("5580", "Wavreille", "", "", "")
    pg.city("5590", "Achêne", "", "", "")
    pg.city("5590", "Braibant", "", "", "")
    pg.city("5590", "Chevetogne", "", "", "")
    pg.city("5590", "Ciney", "", "", "")
    pg.city("5590", "Conneux", "", "", "")
    pg.city("5590", "Haversin", "", "", "")
    pg.city("5590", "Leignon", "", "", "")
    pg.city("5590", "Pessoux", "", "", "")
    pg.city("5590", "Serinchamps", "", "", "")
    pg.city("5590", "Sovet", "", "", "")
    pg.city("5600", "Fagnolle", "", "", "")
    pg.city("5600", "Franchimont", "", "", "")
    pg.city("5600", "Jamagne", "", "", "")
    pg.city("5600", "Jamiolle", "", "", "")
    pg.city("5600", "Merlemont", "", "", "")
    pg.city("5600", "Neuville (Philippeville)", "", "", "")
    pg.city("5600", "Omezée", "", "", "")
    pg.city("5600", "Philippeville", "", "", "")
    pg.city("5600", "Roly", "", "", "")
    pg.city("5600", "Romedenne", "", "", "")
    pg.city("5600", "Samart", "", "", "")
    pg.city("5600", "Sart-en-Fagne", "", "", "")
    pg.city("5600", "Sautour", "", "", "")
    pg.city("5600", "Surice", "", "", "")
    pg.city("5600", "Villers-en-Fagne", "", "", "")
    pg.city("5600", "Villers-le-Gambon", "", "", "")
    pg.city("5600", "Vodecée", "", "", "")
    pg.city("5620", "Corenne", "", "", "")
    pg.city("5620", "Flavion", "", "", "")
    pg.city("5620", "Florennes", "", "", "")
    pg.city("5620", "Hemptinne-lez-Florennes", "", "", "")
    pg.city("5620", "Morville", "", "", "")
    pg.city("5620", "Rosée", "", "", "")
    pg.city("5620", "Saint-Aubin", "", "", "")
    pg.city("5621", "Hanzinelle", "", "", "")
    pg.city("5621", "Hanzinne", "", "", "")
    pg.city("5621", "Morialmé", "", "", "")
    pg.city("5621", "Thy-le-Bauduin", "", "", "")
    pg.city("5630", "Cerfontaine", "", "", "")
    pg.city("5630", "Daussois", "", "", "")
    pg.city("5630", "Senzeille", "", "", "")
    pg.city("5630", "Silenrieux", "", "", "")
    pg.city("5630", "Soumoy", "", "", "")
    pg.city("5630", "Villers-Deux-Eglises", "", "", "")
    pg.city("5640", "Biesme", "", "", "")
    pg.city("5640", "Biesmerée", "", "", "")
    pg.city("5640", "Graux", "", "", "")
    pg.city("5640", "Mettet", "", "", "")
    pg.city("5640", "Oret", "", "", "")
    pg.city("5640", "Saint-Gérard", "", "", "")
    pg.city("5641", "Furnaux", "", "", "")
    pg.city("5644", "Ermeton-sur-Biert", "", "", "")
    pg.city("5646", "Stave", "", "", "")
    pg.city("5650", "Castillon", "", "", "")
    pg.city("5650", "Chastrès", "", "", "")
    pg.city("5650", "Clermont (Nam.)", "", "", "")
    pg.city("5650", "Fontenelle", "", "", "")
    pg.city("5650", "Fraire", "", "", "")
    pg.city("5650", "Pry", "", "", "")
    pg.city("5650", "Vogenée", "", "", "")
    pg.city("5650", "Walcourt", "", "", "")
    pg.city("5650", "Yves-Gomezée", "", "", "")
    pg.city("5651", "Berzée", "", "", "")
    pg.city("5651", "Gourdinne", "", "", "")
    pg.city("5651", "Laneffe", "", "", "")
    pg.city("5651", "Rognée", "", "", "")
    pg.city("5651", "Somzée", "", "", "")
    pg.city("5651", "Tarcienne", "", "", "")
    pg.city("5651", "Thy-le-Château", "", "", "")
    pg.city("5660", "Aublain", "", "", "")
    pg.city("5660", "Boussu-en-Fagne", "", "", "")
    pg.city("5660", "Brûly", "", "", "")
    pg.city("5660", "Brûly-de-Pesche", "", "", "")
    pg.city("5660", "Couvin", "", "", "")
    pg.city("5660", "Cul-des-Sarts", "", "", "")
    pg.city("5660", "Dailly", "", "", "")
    pg.city("5660", "Frasnes (Nam.)", "", "", "")
    pg.city("5660", "Gonrieux", "", "", "")
    pg.city("5660", "Mariembourg", "", "", "")
    pg.city("5660", "Pesche", "", "", "")
    pg.city("5660", "Petigny", "", "", "")
    pg.city("5660", "Petite-Chapelle", "", "", "")
    pg.city("5660", "Presgaux", "", "", "")
    pg.city("5670", "Dourbes", "", "", "")
    pg.city("5670", "Le Mesnil", "", "", "")
    pg.city("5670", "Mazée", "", "", "")
    pg.city("5670", "Nismes", "", "", "")
    pg.city("5670", "Oignies-en-Thiérache", "", "", "")
    pg.city("5670", "Olloy-sur-Viroin", "", "", "")
    pg.city("5670", "Treignes", "", "", "")
    pg.city("5670", "Vierves-sur-Viroin", "", "", "")
    pg.city("5670", "Viroinval", "", "", "")
    pg.city("5680", "Doische", "", "", "")
    pg.city("5680", "Gimnée", "", "", "")
    pg.city("5680", "Gochenée", "", "", "")
    pg.city("5680", "Matagne-la-Grande", "", "", "")
    pg.city("5680", "Matagne-la-Petite", "", "", "")
    pg.city("5680", "Niverlée", "", "", "")
    pg.city("5680", "Romerée", "", "", "")
    pg.city("5680", "Soulme", "", "", "")
    pg.city("5680", "Vaucelles", "", "", "")
    pg.city("5680", "Vodelée", "", "", "")
