# -*- coding: UTF-8 -*-
# Copyright 2014 Luc Saffre
# This file is part of the commondata library.
# The commondata library is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
# The commondata library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with the commondata library; if not, see
# <http://www.gnu.org/licenses/>.


from __future__ import unicode_literals


def populate(pg):

    pg.set_args('fr nl de en')
    pg.province("Brabant flamant", "Vlaams-Brabant", "Flämisch-Brabant", "Brabant flamant")
    
    pg.set_args('zip_code fr nl de en')

    pg.city("3000", "Louvain", "Leuven", "Löwen", "Löwen")
    pg.city("3001", "Heverlee", "", "", "")
    pg.city("3010", "Kessel-Lo", "", "", "")
    pg.city("3012", "Wilsele", "", "", "")
    pg.city("3018", "Wijgmaal (Bt.)", "", "", "")
    pg.city("3020", "Herent", "", "", "")
    pg.city("3020", "Veltem-Beisem", "", "", "")
    pg.city("3020", "Winksele", "", "", "")
    pg.city("3040", "Huldenberg", "", "", "")
    pg.city("3040", "Loonbeek", "", "", "")
    pg.city("3040", "Neerijse", "", "", "")
    pg.city("3040", "Ottenburg", "", "", "")
    pg.city("3040", "Sint-Agatha-Rode", "", "", "")
    pg.city("3050", "Oud-Heverlee", "", "", "")
    pg.city("3051", "Sint-Joris-Weert", "", "", "")
    pg.city("3052", "Blanden", "", "", "")
    pg.city("3053", "Haasrode", "", "", "")
    pg.city("3054", "Vaalbeek", "", "", "")
    pg.city("3060", "Bertem", "", "", "")
    pg.city("3060", "Korbeek-Dijle", "", "", "")
    pg.city("3061", "Leefdaal", "", "", "")
    pg.city("3070", "Kortenberg", "", "", "")
    pg.city("3071", "Erps-kwerps", "", "", "")
    pg.city("3078", "Everberg", "", "", "")
    pg.city("3078", "Meerbeek", "", "", "")
    pg.city("3080", "Duisburg", "", "", "")
    pg.city("3080", "Tervuren", "", "", "")
    pg.city("3080", "Vossem", "", "", "")
    pg.city("3090", "Overijse", "", "", "")
    pg.city("3110", "Rotselaar", "", "", "")
    pg.city("3111", "Wezemaal", "", "", "")
    pg.city("3118", "Werchter", "", "", "")
    pg.city("3120", "Tremelo", "", "", "")
    pg.city("3128", "Baal", "", "", "")
    pg.city("3130", "Begijnendijk", "", "", "")
    pg.city("3130", "Betekom", "", "", "")
    pg.city("3140", "Keerbergen", "", "", "")
    pg.city("3150", "Haacht", "", "", "")
    pg.city("3150", "Tildonk", "", "", "")
    pg.city("3150", "Wespelaar", "", "", "")
    pg.city("3190", "Boortmeerbeek", "", "", "")
    pg.city("3191", "Hever", "", "", "")
    
    pg.city("3200", "Aarschot", "", "", "")
    pg.city("3200", "Gelrode", "", "", "")
    pg.city("3201", "Langdorp", "", "", "")
    pg.city("3202", "Rillaar", "", "", "")
    pg.city("3210", "Linden", "", "", "")
    pg.city("3210", "Lubbeek", "", "", "")
    pg.city("3211", "Binkom", "", "", "")
    pg.city("3212", "Pellenberg", "", "", "")
    pg.city("3220", "Holsbeek", "", "", "")
    pg.city("3220", "Kortrijk-Dutsel", "", "", "")
    pg.city("3220", "Sint-Pieters-Rode", "", "", "")
    pg.city("3221", "Nieuwrode", "", "", "")
    pg.city("3270", "Montaigu", "Scherpenheuvel", "Montaigu", "Montaigu")
    pg.city("3271", "Averbode", "", "", "")
    pg.city("3271", "Zichem", "", "", "")
    pg.city("3272", "Messelbroek", "", "", "")
    pg.city("3272", "Testelt", "", "", "")
    pg.city("3290", "Deurne (Bt.)", "", "", "")
    pg.city("3290", "Diest", "", "", "")
    pg.city("3290", "Schaffen", "", "", "")
    pg.city("3290", "Webbekom", "", "", "")
    pg.city("3293", "Kaggevinne", "", "", "")
    pg.city("3294", "Molenstede", "", "", "")
    pg.city("3300", "Bost", "", "", "")
    pg.city("3300", "Goetsenhoven", "", "", "")
    pg.city("3300", "Hakendover", "", "", "")
    pg.city("3300", "Kumtich", "", "", "")
    pg.city("3300", "Oorbeek", "", "", "")
    pg.city("3300", "Oplinter", "", "", "")
    pg.city("3300", "St-Margriete-Houtem(Tien.)", "", "", "")
    pg.city("3300", "Tienen", "", "", "")
    pg.city("3300", "Vissenaken", "", "", "")
    pg.city("3320", "Hoegaarden", "", "", "")
    pg.city("3320", "Meldert (Bt.)", "", "", "")
    pg.city("3321", "Outgaarden", "", "", "")
    pg.city("3350", "Drieslinter", "", "", "")
    pg.city("3350", "Linter", "", "", "")
    pg.city("3350", "Melkwezer", "", "", "")
    pg.city("3350", "Neerhespen", "", "", "")
    pg.city("3350", "Neerlinter", "", "", "")
    pg.city("3350", "Orsmaal-Gussenhoven", "", "", "")
    pg.city("3350", "Overhespen", "", "", "")
    pg.city("3350", "Wommersom", "", "", "")
    pg.city("3360", "Bierbeek", "", "", "")
    pg.city("3360", "Korbeek-Lo", "", "", "")
    pg.city("3360", "Lovenjoel", "", "", "")
    pg.city("3360", "Opvelp", "", "", "")
    pg.city("3370", "Boutersem", "", "", "")
    pg.city("3370", "Kerkom", "", "", "")
    pg.city("3370", "Neervelp", "", "", "")
    pg.city("3370", "Roosbeek", "", "", "")
    pg.city("3370", "Vertrijk", "", "", "")
    pg.city("3370", "Willebringen", "", "", "")
    pg.city("3380", "Bunsbeek", "", "", "")
    pg.city("3380", "Glabbeek(Zuurbemde)", "", "", "")
    pg.city("3381", "Kapellen (Bt.)", "", "", "")
    pg.city("3384", "Attenrode", "", "", "")
    pg.city("3390", "Houwaart", "", "", "")
    pg.city("3390", "Sint-Joris-Winge", "", "", "")
    pg.city("3390", "Tielt (Bt.)", "", "", "")
    pg.city("3391", "Meensel-Kiezegem", "", "", "")
    pg.city("3400", "Eliksem", "", "", "")
    pg.city("3400", "Ezemaal", "", "", "")
    pg.city("3400", "Laar", "", "", "")
    pg.city("3400", "Landen", "", "", "")
    pg.city("3400", "Neerwinden", "", "", "")
    pg.city("3400", "Overwinden", "", "", "")
    pg.city("3400", "Rumsdorp", "", "", "")
    pg.city("3400", "Wange", "", "", "")
    pg.city("3401", "Waasmont", "", "", "")
    pg.city("3401", "Walsbets", "", "", "")
    pg.city("3401", "Walshoutem", "", "", "")
    pg.city("3401", "Wezeren", "", "", "")
    pg.city("3404", "Attenhoven", "", "", "")
    pg.city("3404", "Neerlanden", "", "", "")
    pg.city("3440", "Budingen", "", "", "")
    pg.city("3440", "Dormaal", "", "", "")
    pg.city("3440", "Halle-Booienhoven", "", "", "")
    pg.city("3440", "Helen-Bos", "", "", "")
    pg.city("3440", "Léau", "Zoutleeuw", "Léau", "Léau")
    pg.city("3450", "Geetbets", "", "", "")
    pg.city("3450", "Grazen", "", "", "")
    pg.city("3454", "Rummen", "", "", "")
    pg.city("3460", "Assent", "", "", "")
    pg.city("3460", "Bekkevoort", "", "", "")
    pg.city("3461", "Molenbeek-Wersbeek", "", "", "")
    pg.city("3470", "Kortenaken", "", "", "")
    pg.city("3470", "Ransberg", "", "", "")
    pg.city("3470", "St-Margriete (Kortenaken)", "", "", "")
    pg.city("3471", "Hoeleden", "", "", "")
    pg.city("3472", "Kersbeek-Miskom", "", "", "")
    pg.city("3473", "Waanrode", "", "", "")
    pg.city("3500", "Hasselt", "", "", "")
    pg.city("3500", "Sint-Lambrechts-Herk", "", "", "")
    pg.city("3501", "Wimmertingen", "", "", "")
    pg.city("3510", "Kermt", "", "", "")
    pg.city("3510", "Spalbeek", "", "", "")
    pg.city("3511", "Kuringen", "", "", "")
    pg.city("3511", "Stokrooie", "", "", "")
    pg.city("3512", "Stevoort", "", "", "")
    pg.city("3520", "Zonhoven", "", "", "")
    pg.city("3530", "Helchteren", "", "", "")
    pg.city("3530", "Houthalen", "", "", "")
    pg.city("3530", "Houthalen-Helchteren", "", "", "")
    pg.city("3540", "Berbroek", "", "", "")
    pg.city("3540", "Donk", "", "", "")
    pg.city("3540", "Schulen", "", "", "")
    pg.city("3540", "Herck-la-Ville", "Herk-de-Stad", "Herk-de-Stad", "Herk-de-Stad")
    pg.city("3545", "Halen", "", "", "")
    pg.city("3545", "Loksbergen", "", "", "")
    pg.city("3545", "Zelem", "", "", "")
    pg.city("3550", "Heusden (Limb.)", "", "", "")
    pg.city("3550", "Heusden-Zolder", "", "", "")
    pg.city("3550", "Zolder", "", "", "")
    pg.city("3560", "Linkhout", "", "", "")
    pg.city("3560", "Lummen", "", "", "")
    pg.city("3560", "Meldert (Limb.)", "", "", "")
    pg.city("3570", "Alken", "", "", "")
    pg.city("3580", "Beringen", "", "", "")
    pg.city("3581", "Beverlo", "", "", "")
    pg.city("3582", "Koersel", "", "", "")
    pg.city("3583", "Paal", "", "", "")
    pg.city("3590", "Diepenbeek", "", "", "")
    pg.city("3600", "Genk", "", "", "")
    pg.city("3620", "Gellik", "", "", "")
    pg.city("3620", "Lanaken", "", "", "")
    pg.city("3620", "Neerharen", "", "", "")
    pg.city("3620", "Veldwezelt", "", "", "")
    pg.city("3621", "Rekem", "", "", "")
    pg.city("3630", "Eisden", "", "", "")
    pg.city("3630", "Leut", "", "", "")
    pg.city("3630", "Maasmechelen", "", "", "")
    pg.city("3630", "Mechelen-aan-de-Maas", "", "", "")
    pg.city("3630", "Meeswijk", "", "", "")
    pg.city("3630", "Opgrimbie", "", "", "")
    pg.city("3630", "Vucht", "", "", "")
    pg.city("3631", "Boorsem", "", "", "")
    pg.city("3631", "Uikhoven", "", "", "")
    pg.city("3640", "Kessenich", "", "", "")
    pg.city("3640", "Kinrooi", "", "", "")
    pg.city("3640", "Molenbeersel", "", "", "")
    pg.city("3640", "Ophoven", "", "", "")
    pg.city("3650", "Dilsen", "", "", "")
    pg.city("3650", "Elen", "", "", "")
    pg.city("3650", "Lanklaar", "", "", "")
    pg.city("3650", "Rotem", "", "", "")
    pg.city("3650", "Stokkem", "", "", "")
    pg.city("3660", "Opglabbeek", "", "", "")
    pg.city("3665", "As", "", "", "")
    pg.city("3668", "Niel-bij-As", "", "", "")
    pg.city("3670", "Ellikom", "", "", "")
    pg.city("3670", "Gruitrode", "", "", "")
    pg.city("3670", "Meeuwen", "", "", "")
    pg.city("3670", "Meeuwen-Gruitrode", "", "", "")
    pg.city("3670", "Neerglabbeek", "", "", "")
    pg.city("3670", "Wijshagen", "", "", "")
    pg.city("3680", "Maaseik", "", "", "")
    pg.city("3680", "Neeroeteren", "", "", "")
    pg.city("3680", "Opoeteren", "", "", "")
    pg.city("3690", "Zutendaal", "", "", "")
    pg.city("3700", "Berg (Limb.)", "", "", "")
    pg.city("3700", "Diets-Heur", "", "", "")
    pg.city("3700", "Haren (Tongeren)", "", "", "")
    pg.city("3700", "Henis", "", "", "")
    pg.city("3700", "Kolmont (Tongeren)", "", "", "")
    pg.city("3700", "Koninksem", "", "", "")
    pg.city("3700", "Lauw", "", "", "")
    pg.city("3700", "Mal", "", "", "")
    pg.city("3700", "Neerrepen", "", "", "")
    pg.city("3700", "Nerem", "", "", "")
    pg.city("3700", "Overrepen", "", "", "")
    pg.city("3700", "Piringen", "", "", "")
    pg.city("3700", "Riksingen", "", "", "")
    pg.city("3700", "Rutten", "", "", "")
    pg.city("3700", "'s Herenelderen", "", "", "")
    pg.city("3700", "Sluizen", "", "", "")
    pg.city("3700", "Vreren", "", "", "")
    pg.city("3700", "Widooie", "", "", "")
    pg.city("3700", "Tongres", "Tongeren", "Tongeren", "Tongeren")
    pg.city("3717", "Herstappe", "", "", "")
    pg.city("3720", "Kortessem", "", "", "")
    pg.city("3721", "Vliermaalroot", "", "", "")
    pg.city("3722", "Wintershoven", "", "", "")
    pg.city("3723", "Guigoven", "", "", "")
    pg.city("3724", "Vliermaal", "", "", "")
    pg.city("3730", "Hoeselt", "", "", "")
    pg.city("3730", "Romershoven", "", "", "")
    pg.city("3730", "Sint-Huibrechts-Hern", "", "", "")
    pg.city("3730", "Werm", "", "", "")
    pg.city("3732", "Schalkhoven", "", "", "")
    pg.city("3740", "Beverst", "", "", "")
    pg.city("3740", "Bilzen", "", "", "")
    pg.city("3740", "Eigenbilzen", "", "", "")
    pg.city("3740", "Grote-Spouwen", "", "", "")
    pg.city("3740", "Hees", "", "", "")
    pg.city("3740", "Kleine-Spouwen", "", "", "")
    pg.city("3740", "Mopertingen", "", "", "")
    pg.city("3740", "Munsterbilzen", "", "", "")
    pg.city("3740", "Rijkhoven", "", "", "")
    pg.city("3740", "Rosmeer", "", "", "")
    pg.city("3740", "Waltwilder", "", "", "")
    pg.city("3742", "Martenslinde", "", "", "")
    pg.city("3746", "Hoelbeek", "", "", "")
    pg.city("3770", "Genoelselderen", "", "", "")
    pg.city("3770", "Herderen", "", "", "")
    pg.city("3770", "Kanne", "", "", "")
    pg.city("3770", "Membruggen", "", "", "")
    pg.city("3770", "Millen", "", "", "")
    pg.city("3770", "Riemst", "", "", "")
    pg.city("3770", "Val-Meer", "", "", "")
    pg.city("3770", "Vlijtingen", "", "", "")
    pg.city("3770", "Vroenhoven", "", "", "")
    pg.city("3770", "Zichen-Zussen-Bolder", "", "", "")
    pg.city("3790", "Fouron-Saint-Martin", "", "", "")
    pg.city("3790", "Moelingen", "", "", "")
    pg.city("3790", "Mouland", "", "", "")
    pg.city("3790", "Sint-Martens-Voeren", "", "", "")
    pg.city("3790", "Voeren", "", "", "")
    pg.city("3790", "Fourons", "Voeren", "Fourons", "Fourons")
    pg.city("3791", "Remersdaal", "", "", "")
    pg.city("3792", "Fouron-Saint-Pierre", "", "", "")
    pg.city("3792", "Sint-Pieters-Voeren", "", "", "")
    pg.city("3793", "Teuven", "", "", "")
    pg.city("3798", "Fouron-le-Comte", "", "", "")
    pg.city("3798", "'s Gravenvoeren", "", "", "")
    pg.city("3800", "Brustem", "", "", "")
    pg.city("3800", "Engelmanshoven", "", "", "")
    pg.city("3800", "Gelinden", "", "", "")
    pg.city("3800", "Groot-Gelmen", "", "", "")
    pg.city("3800", "Halmaal", "", "", "")
    pg.city("3800", "Kerkom-bij-Sint-Truiden", "", "", "")
    pg.city("3800", "Ordingen", "", "", "")
    pg.city("3800", "Zepperen", "", "", "")
    pg.city("3800", "Saint-Trond", "Sint-Truiden", "Saint-Trond", "Saint-Trond")
    pg.city("3803", "Duras", "", "", "")
    pg.city("3803", "Gorsem", "", "", "")
    pg.city("3803", "Runkelen", "", "", "")
    pg.city("3803", "Wilderen", "", "", "")
    pg.city("3806", "Velm", "", "", "")
    pg.city("3830", "Berlingen", "", "", "")
    pg.city("3830", "Wellen", "", "", "")
    pg.city("3831", "Herten", "", "", "")
    pg.city("3832", "Ulbeek", "", "", "")
    pg.city("3840", "Bommershoven", "", "", "")
    pg.city("3840", "Borgloon", "", "", "")
    pg.city("3840", "Broekom", "", "", "")
    pg.city("3840", "Gors-Opleeuw", "", "", "")
    pg.city("3840", "Gotem", "", "", "")
    pg.city("3840", "Groot-Loon", "", "", "")
    pg.city("3840", "Haren (Borgloon)", "", "", "")
    pg.city("3840", "Hendrieken", "", "", "")
    pg.city("3840", "Hoepertingen", "", "", "")
    pg.city("3840", "Jesseren", "", "", "")
    pg.city("3840", "Kerniel", "", "", "")
    pg.city("3840", "Kolmont (Borgloon)", "", "", "")
    pg.city("3840", "Kuttekoven", "", "", "")
    pg.city("3840", "Rijkel", "", "", "")
    pg.city("3840", "Voort", "", "", "")
    pg.city("3850", "Binderveld", "", "", "")
    pg.city("3850", "Kozen", "", "", "")
    pg.city("3850", "Nieuwerkerken (Limb.)", "", "", "")
    pg.city("3850", "Wijer", "", "", "")
    pg.city("3870", "Batsheers", "", "", "")
    pg.city("3870", "Bovelingen", "", "", "")
    pg.city("3870", "Gutschoven", "", "", "")
    pg.city("3870", "Heers", "", "", "")
    pg.city("3870", "Heks", "", "", "")
    pg.city("3870", "Horpmaal", "", "", "")
    pg.city("3870", "Klein-Gelmen", "", "", "")
    pg.city("3870", "Mechelen-Bovelingen", "", "", "")
    pg.city("3870", "Mettekoven", "", "", "")
    pg.city("3870", "Opheers", "", "", "")
    pg.city("3870", "Rukkelingen-Loon", "", "", "")
    pg.city("3870", "Vechmaal", "", "", "")
    pg.city("3870", "Veulen", "", "", "")
    pg.city("3890", "Boekhout", "", "", "")
    pg.city("3890", "Gingelom", "", "", "")
    pg.city("3890", "Jeuk", "", "", "")
    pg.city("3890", "Kortijs", "", "", "")
    pg.city("3890", "Montenaken", "", "", "")
    pg.city("3890", "Niel-bij-Sint-Truiden", "", "", "")
    pg.city("3890", "Vorsen", "", "", "")
    pg.city("3891", "Borlo", "", "", "")
    pg.city("3891", "Buvingen", "", "", "")
    pg.city("3891", "Mielen-boven-Aalst", "", "", "")
    pg.city("3891", "Muizen (Limb.)", "", "", "")
    pg.city("3900", "Overpelt", "", "", "")
    pg.city("3910", "Neerpelt", "", "", "")
    pg.city("3910", "Sint-Huibrechts-Lille", "", "", "")
    pg.city("3920", "Lommel", "", "", "")
    pg.city("3930", "Achel", "", "", "")
    pg.city("3930", "Hamont", "", "", "")
    pg.city("3930", "Hamont-Achel", "", "", "")
    pg.city("3940", "Hechtel", "", "", "")
    pg.city("3941", "Eksel", "", "", "")
    pg.city("3945", "Ham", "", "", "")
    pg.city("3945", "Kwaadmechelen", "", "", "")
    pg.city("3945", "Oostham", "", "", "")
    pg.city("3950", "Bocholt", "", "", "")
    pg.city("3950", "Kaulille", "", "", "")
    pg.city("3950", "Reppel", "", "", "")
    pg.city("3960", "Beek", "", "", "")
    pg.city("3960", "Bree", "", "", "")
    pg.city("3960", "Gerdingen", "", "", "")
    pg.city("3960", "Opitter", "", "", "")
    pg.city("3960", "Tongerlo (Limb.)", "", "", "")
    pg.city("3970", "Leopoldsburg", "", "", "")
    pg.city("3971", "Heppen", "", "", "")
    pg.city("3980", "Tessenderlo", "", "", "")
    pg.city("3990", "Grote-Brogel", "", "", "")
    pg.city("3990", "Kleine-Brogel", "", "", "")
    pg.city("3990", "Peer", "", "", "")
    pg.city("3990", "Wijchmaal", "", "", "")
    
