
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.0'
version_full = 'd52f066a18217e40395523713bb497d3bbc982d6'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

