
# transactionStatus codes

INITIAL = 0
TO_VALIDATE = 1
TO_FORCE = 2
TO_VALIDATE_AND_AUTHORIZE = 3
WAITING_FOR_DELIVERY = 4
WAITING_FOR_AUTHORIZATION = 5
DELIVERED = 6
EXPIRED = 7
REFUSED = 8
CANCELED = 9
DELIVERY_IN_PROGRESS = 11
AUTJORIZATION_IN_PROGRESS = 12
FAILURE = 13
