
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.1'
version_full = 'd99faf5a5fff5f9fac7b02204e8de361b6750e0e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

