
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.6'
version_full = 'fc96295fffc0c93fb4478edd1d5866188f97b81a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

