__version__ = "0.1.4"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1d898ddc27a327a778c454f7d4250d68012552e9'
__git_head_subject__ = 'fix in _extract_protection_group'
__git_head_message__ = ''
__git_dirty_diff__ = ''