from tests.tests.feincms_ import *
from tests.tests.fields import *
from tests.tests.markup_base import *
from tests.tests.markup_html import *
from tests.tests.markup_markdown import *
from tests.tests.markup_plaintext import *
from tests.tests.markup_restructuredtext import *
from tests.tests.markup_textile import *
from tests.tests.version import *
from tests.tests.views import *
from tests.tests.widgets import *
