__version__ = "0.3.32"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.32)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '92f52d09c1248e3fa3d70fe6ac78a2b2b53e7928'
__git_head_subject__ = 'STORAGEMODEL-311 target_port_group and relative_target_port_identifier fields in rtpg.py need to be unsigned'
__git_head_message__ = ''
__git_dirty_diff__ = ''