# Test Hypotheses
#----------------------------
GREATER_THAN_HYPOTHESIS = 'greater'
LESS_THAN_HYPOTHESIS = 'less'
TWO_SIDED_HYPOTHESIS = 'two.sided'
TEST_HYPOTHESES = frozenset([GREATER_THAN_HYPOTHESIS, LESS_THAN_HYPOTHESIS, TWO_SIDED_HYPOTHESIS])
