__version__ = "0.3.28"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.28)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '571062cd3a870d64f3a95475ef607cf1a354d680'
__git_head_subject__ = 'TRIVIAL removing unsued imports'
__git_head_message__ = ''
__git_dirty_diff__ = ''