__version__ = "0.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8641ccfc90f2df535d0f350fba8d91993701de72'
__git_head_subject__ = 'SafePool'
__git_head_message__ = ''
__git_dirty_diff__ = ''