__version__ = "0.4.25"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.4.25)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd0715288638ad7985574ff7b55a930c10709d70f'
__git_head_subject__ = 'fix PyPI.get_all_packages'
__git_head_message__ = ''
__git_dirty_diff__ = ''