
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4'
version_full = 'ac8af0c608e7cb22b02bef3b25256bf08d939237'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

