from distutils.core import setup
setup(name = "appy", version = "0.9.1",
      description = "The Appy framework",
      long_description = "Appy builds simple but complex web Python apps.",
      author = "Gaetan Delannay",
      author_email = "gaetan.delannay AT geezteem.com",
      license = "GPL", platforms="all",
      url = 'http://appyframework.org',
      packages = ["appy","appy.fields","appy.bin","appy.gen","appy.gen.ui","appy.gen.ui.jscalendar","appy.gen.ui.jscalendar.lang","appy.gen.ui.jscalendar.skins","appy.gen.ui.jscalendar.skins.tiger","appy.gen.ui.jscalendar.skins.aqua","appy.gen.ui.ckeditor","appy.gen.ui.ckeditor.plugins","appy.gen.ui.ckeditor.plugins.magicline","appy.gen.ui.ckeditor.plugins.magicline.images","appy.gen.ui.ckeditor.plugins.magicline.images.hidpi","appy.gen.ui.ckeditor.plugins.table","appy.gen.ui.ckeditor.plugins.table.dialogs","appy.gen.ui.ckeditor.plugins.wsc","appy.gen.ui.ckeditor.plugins.wsc.dialogs","appy.gen.ui.ckeditor.plugins.a11yhelp","appy.gen.ui.ckeditor.plugins.a11yhelp.dialogs","appy.gen.ui.ckeditor.plugins.a11yhelp.dialogs.lang","appy.gen.ui.ckeditor.plugins.tabletools","appy.gen.ui.ckeditor.plugins.tabletools.dialogs","appy.gen.ui.ckeditor.plugins.pastefromword","appy.gen.ui.ckeditor.plugins.pastefromword.filter","appy.gen.ui.ckeditor.plugins.scayt","appy.gen.ui.ckeditor.plugins.scayt.dialogs","appy.gen.ui.ckeditor.plugins.clipboard","appy.gen.ui.ckeditor.plugins.clipboard.dialogs","appy.gen.ui.ckeditor.plugins.image","appy.gen.ui.ckeditor.plugins.image.images","appy.gen.ui.ckeditor.plugins.image.dialogs","appy.gen.ui.ckeditor.plugins.link","appy.gen.ui.ckeditor.plugins.link.images","appy.gen.ui.ckeditor.plugins.link.images.hidpi","appy.gen.ui.ckeditor.plugins.link.dialogs","appy.gen.ui.ckeditor.plugins.dialog","appy.gen.ui.ckeditor.plugins.specialchar","appy.gen.ui.ckeditor.plugins.specialchar.dialogs","appy.gen.ui.ckeditor.plugins.specialchar.dialogs.lang","appy.gen.ui.ckeditor.plugins.about","appy.gen.ui.ckeditor.plugins.about.dialogs","appy.gen.ui.ckeditor.plugins.about.dialogs.hidpi","appy.gen.ui.ckeditor.lang","appy.gen.ui.ckeditor.skins","appy.gen.ui.ckeditor.skins.moono","appy.gen.ui.ckeditor.skins.moono.images","appy.gen.ui.ckeditor.skins.moono.images.hidpi","appy.gen.templates","appy.gen.tr","appy.gen.wrappers","appy.gen.mixins","appy.px","appy.shared","appy.shared.data","appy.pod","appy.pod.test","appy.pod.test.templates","appy.pod.test.contexts","appy.pod.test.images","appy.pod.test.results"],
      package_data = {'':["*.*"]})
