
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.6'
version_full = 'd6e0c2e9767c8b3c76e1643c056d2ff9bee1d12e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

