
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.16'
version_full = '86faa64ff1f0a82dcb108bb4838da43bc0a9fc95'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

