# This file was auto-generated by salt's setup on Friday, 31 October 2014 @ 17:10:32 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2014, 7, 0, 0, 7, 0, None)
