
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.3'
version_full = '2e0967d622e97469660447a86897771049901316'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

