
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.0a3'
version_full = 'b38507b85793e77a80d9d401a6825ee58ac920e1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

