
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.0'
version_full = '9e89e4fc8dba7541f3475de0183b47fa9342ea84'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

