
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4rc2'
version_full = '1277e41f36e4f53081ec03e9f283fd2674225e8c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

