
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.1rc1'
version_full = '516d68e6e2f1d40df1fa25d15628450b9def8210'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

