
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.2'
version_full = '9d45a2a53382b4b5cf2a7ff0883e9250aa907f91'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

