
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4-41-gfa759bc'
version_full = 'fa759bc49f421d86c5b3c93be44a4f466fc3e8c1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

