
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4rc5'
version_full = 'c9bbaaf9e7d312e3c336f33bd00dcc0f938bb745'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

