
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.1'
version_full = 'ba31f9f7e6150c4ca42c7ca1ce4c1d2de5bce3f0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

