
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.2'
version_full = '41ee776fff363da8b5beb00dee74b8c671b44989'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

