__version__ = "0.6.16"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.6.16)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd08aa0485ba253859653f4a04338fbf460d7cff7'
__git_head_subject__ = 'Finished release v0.6.16.'
__git_head_message__ = ''
__git_dirty_diff__ = ''