
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4'
version_full = '9f3e00436796fb618f5113017ef8d9939fb20c79'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

