
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.2'
version_full = '0537b73c3a635cb5de7287c0f8bb4b5994a7a2f0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

