
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3'
version_full = '2ecb0d246679db7d1c6d986d628f8c88503140bb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

