# This file was auto-generated by salt's setup on Thursday, 23 October 2014 @ 02:10:34 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2014, 7, 0, 0, 6, 0, None)
