
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9'
version_full = 'c86cdf75a01f20bab81580d52f902560cbbd70fa'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

