'''
Created on 3/11/2014

@author: hashtonmartyn
'''
GPS_INVALID_FIX = "GPS_INVALID_FIX"
GPS_SPS_FIX = "GPS_SPS_FIX"
GPS_INVALID_SOLUTION = "GPS_INVALID_SOLUTION"
GPS_AUTONOMOUS_SOLUTION = "GPS_AUTONOMOUS_SOLUTION"