
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0a3'
version_full = 'faef56ce2ea1062ebfee0f6d1876cc77e1341c1d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

