
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.3'
version_full = '848e54b60126dd022b0e5e632d6d82f87f563627'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

