__version__ = "0.1.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '971217ac3fac23077ba31dee311240fba35d885f'
__git_head_subject__ = 'Finished release v0.1.1.'
__git_head_message__ = '* release/v0.1.1:\n  more fixes\n  fixing relative import\n  some fixes\n  purge'
__git_dirty_diff__ = ''