
# This file was generated by 'versioneer.py' (0.11) from revision-control system data, or from the parent directory name of
# an unpacked source archive. Distribution tarballs contain a pre-generated copy of this file.

version_version = '4.0.0'
version_full = '49b7b0182e902e8d0a1535228c19f9696be93c95'
def get_versions(default={}, verbose=False):
   return {'version': version_version, 'full': version_full}
