__version__ = "0.2.8"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'edf2d363f1f15abdce8dc9a8012f379ad8915df9'
__git_head_subject__ = 'HOSTDEV-1732'
__git_head_message__ = ''
__git_dirty_diff__ = ''