
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.0a1'
version_full = '719954114e5dd19f8e4649c880c66887067378b3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

