__version__ = "0.2.4"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '45018ce6724abd0d71f876590f4f351aab3f1dec'
__git_head_subject__ = 'Finished release v0.2.4.'
__git_head_message__ = '* release/v0.2.4:\n  notify_related_tickets\n  redirection'
__git_dirty_diff__ = ''