# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distopt/worker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import distopt.data_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='distopt/worker.proto',
  package='',
  serialized_pb=_b('\n\x14\x64istopt/worker.proto\x1a\x12\x64istopt/data.proto\"C\n\x14\x41pplyOperatorRequest\x12\x13\n\x0bop_location\x18\x01 \x01(\t\x12\x16\n\x05input\x18\x02 \x01(\x0b\x32\x07.Vector\"\x87\x01\n\x15\x41pplyOperatorResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.ApplyOperatorResponse.Status\x12\x17\n\x06output\x18\x02 \x01(\x0b\x32\x07.Vector\"&\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x14\n\x10INVALID_OPERATOR\x10\x01\x32H\n\x06Worker\x12>\n\rApplyOperator\x12\x15.ApplyOperatorRequest\x1a\x16.ApplyOperatorResponseB\x03\x80\x01\x01')
  ,
  dependencies=[distopt.data_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_APPLYOPERATORRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ApplyOperatorResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_OPERATOR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=211,
  serialized_end=249,
)
_sym_db.RegisterEnumDescriptor(_APPLYOPERATORRESPONSE_STATUS)


_APPLYOPERATORREQUEST = _descriptor.Descriptor(
  name='ApplyOperatorRequest',
  full_name='ApplyOperatorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_location', full_name='ApplyOperatorRequest.op_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='ApplyOperatorRequest.input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=111,
)


_APPLYOPERATORRESPONSE = _descriptor.Descriptor(
  name='ApplyOperatorResponse',
  full_name='ApplyOperatorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ApplyOperatorResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='ApplyOperatorResponse.output', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _APPLYOPERATORRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=249,
)

_APPLYOPERATORREQUEST.fields_by_name['input'].message_type = distopt.data_pb2._VECTOR
_APPLYOPERATORRESPONSE.fields_by_name['status'].enum_type = _APPLYOPERATORRESPONSE_STATUS
_APPLYOPERATORRESPONSE.fields_by_name['output'].message_type = distopt.data_pb2._VECTOR
_APPLYOPERATORRESPONSE_STATUS.containing_type = _APPLYOPERATORRESPONSE
DESCRIPTOR.message_types_by_name['ApplyOperatorRequest'] = _APPLYOPERATORREQUEST
DESCRIPTOR.message_types_by_name['ApplyOperatorResponse'] = _APPLYOPERATORRESPONSE

ApplyOperatorRequest = _reflection.GeneratedProtocolMessageType('ApplyOperatorRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPLYOPERATORREQUEST,
  __module__ = 'distopt.worker_pb2'
  # @@protoc_insertion_point(class_scope:ApplyOperatorRequest)
  ))
_sym_db.RegisterMessage(ApplyOperatorRequest)

ApplyOperatorResponse = _reflection.GeneratedProtocolMessageType('ApplyOperatorResponse', (_message.Message,), dict(
  DESCRIPTOR = _APPLYOPERATORRESPONSE,
  __module__ = 'distopt.worker_pb2'
  # @@protoc_insertion_point(class_scope:ApplyOperatorResponse)
  ))
_sym_db.RegisterMessage(ApplyOperatorResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001'))
# @@protoc_insertion_point(module_scope)
