__version__ = "0.3.31"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.31)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '34f0030138d6f7ee56cf6d15a5919ed561d610ff'
__git_head_subject__ = 'HOSTDEV-1933 some inquiry fixes'
__git_head_message__ = ''
__git_dirty_diff__ = ''