
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4rc4'
version_full = '5fd86aecf723aed75ca3b496fac36d020cae860c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

