__version__ = "0.5.16"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.5.16)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'feac70d630f78c33f3175617fa9e11459b8f270f'
__git_head_subject__ = 'Finished release v0.5.16.'
__git_head_message__ = '* release/v0.5.16:\n  TRIVIAL fixing tests\n  TRIVIAL more fixes\n  TRIVIAL more fixes\n  TRIVIAL fixing get_scons_variables__windows\n  TRIVIAL fixing get_scons_variables__linux and get_scons_variables__osx\n  TRIVIAL fixing get_scons_variables__linux and get_scons_variables__osx\n  HOSTDEV-1834 adding support for signing the embedded executables'
__git_dirty_diff__ = ''