
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.3c1'
version_full = 'd6123b1e47374499f004187353c4bc737093b50a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

