
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.1'
version_full = 'ed3128e3bdde04ac9ef3a541bae8deff587d17c4'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

