__version__ = "0.1.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8959242d851dc9bdd098cb7805d410e1617cf3bb'
__git_head_subject__ = 'Finished release v0.1.3.'
__git_head_message__ = '* release/v0.1.3:\n  another fix in _retreive_properties\n  a better handling of possible None return value from collector.RetrievePropertiesEx\n  EsxCLI: changing the MMESoapStubAdapter.versionId to the ESX api version, not the vSphere API version - they can be different\n  handling possible None return value from collector.RetrievePropertiesEx'
__git_dirty_diff__ = ''