
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.0'
version_full = '63f189a75ebafa7d705a90d017779fe86c8fb357'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

