options = (
    ('hg-server-max-tries',
     {'type' : 'int',
      'default': 5,
      'help': 'number of tries to acquire filesystem lock in mercurial-server hgadmin repo mercurial operations',
      'group': 'mercurial_server',
      'level': 2,
      }),
    ('hg-server-lock-wait-seconds',
     {'type' : 'float',
      'default': 1.,
      'help': 'number of seconds to wait between each filesystem lock acquisition (see hg-server-max-lock-wait)',
      'group': 'mercurial_server',
      'level': 2,
      }),
    ('hg-server-lock-kill-seconds',
     {'type' : 'float',
      'default': 10.,
      'help': 'number of seconds the lock file may exist before its removal is forced',
      'group': 'mercurial_server',
      'level': 2,
      }),
    ('hg-ssh',
     {'type': 'string',
      'default': None,
      'help': 'ssh argument passed to hglib commands',
      'group': 'mercurial_server',
      'level': 2,
      }),
    )
