
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2'
version_full = '73ed26db1526446d2476579296789bab58d9d196'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

