__version__ = "0.5.11"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "yalon@infinidat.com"
__git_branch__ = '(detached from v0.5.11)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '0435a01fdb3436af2a42a6e8f2cd197de76eac31'
__git_head_subject__ = 'Finished release v0.5.11.'
__git_head_message__ = ''
__git_dirty_diff__ = ''