
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.3.2'
version_full = '7c2d060fca1070051c597d519a1dca27fafdb738'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

