
# This file was generated by 'versioneer.py' (0.10+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.7.4'
version_full = 'd9168c2110d7b8fa8cf4813d00f32f203e5f709f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

