__version__ = "0.1.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '15ef23162617a833d52edb598c5c1f0b99ab42b9'
__git_head_subject__ = 'HOSTDEV-1928 using a private old copy of parse_version'
__git_head_message__ = ''
__git_dirty_diff__ = ''