__version__ = "0.5.22"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.5.22)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'b876ff9cf025d96197907bc8c9886cd31ef24f35'
__git_head_subject__ = 'Finished release v0.5.22.'
__git_head_message__ = ''
__git_dirty_diff__ = ''