# Base error codes
SUCCESS = 0
REFUSED = 1

TRANSACTION_NOT_FOUND = 2
TRANSACTION_INVALID_STATE = 3
TRANSACTION_ALREADY_EXISTS = 4

INVALID_SIGNATURE = 5
INVALID_DATE = 6
INVALID_AMOUNT = 10
INVALID_CURRENCY = 11
INVALID_CARD_NETWORK = 12
INVALID_EXPIRATION_DATE = 13
INVALID_CVV = 14
UNKNOWN_CONTRACT = 15
INVALID_CARD_NUMBER_ALT = 16

ID_NOT_FOUND = 17
INVALID_ID = 18
SUBSCRIPTION_NOT_FOUND = 19
INVALID_SUSCRIPTION = 20
ID_ALREADY_EXISTS = 21
ID_CREATION_REFUSED = 22
PURGED_ID = 23
NO_CHANGE = 26
UNAUTHORIZED_AMOUNT = 27
RANGE_NOT_FOUND = 40

INVALID_SHOP_ID = 50
INVALID_TRANSMISSION_DATE = 51
INVALID_TRANSACTION_ID = 52
INVALID_CTX_MODE = 53
INVALID_COMMENT = 54
INVALID_AUTO_NB = 55
INVALID_AUTO_DATE = 56
INVALID_PRESENTATION_DATE = 57
INVALID_NEW_TRANSACTION_ID = 58
INVALID_VALIDATION_MODE = 59

INVALID_ORDER_ID = 60
INVALID_ORDER_INFO_1 = 61
INVALID_ORDER_INFO_2 = 62
INVALID_ORDER_INFO_3 = 63

INVALID_PAYMENT_METHOD = 64
INVALID_CARD_NUMBER = 65

INVALID_CONTRACT_NUMBER = 66
INVALID_CUSTOMER_ID = 67
INVALID_CUSTOMER_TITLE = 68
INVALID_CUSTOMER_NAME = 69
INVALID_CUSTOMER_PHONE = 70
INVALID_CUSTOMER_MAIL = 71
INVALID_CUSTOMER_ADDRESS = 72
INVALID_CUSTOMER_ZIPCODE = 73
INVALID_CUSTOMER_CITY = 74
INVALID_CUSTOMER_COUNTRY = 75
INVALID_CUSTOMER_LANGUAGE = 76
INVALID_CUSTOMER_IP = 77
INVALID_CUSTOMER_SEND_MAIL = 78
INVALID_CUSTOMER_MOBILE_PHONE = 79

INVALID_SUB_PAYMENT_TYPE = 80
INVALID_SUB_REF = 81
INVALID_INITIAL_AMOUNT = 82
INVALID_OCC_INITIAL_AMOUNT = 83
INVALID_EFFECT_DATE = 84
INVALID_STATE = 85

INVALID_ENROLLED = 90
INVALID_AUTH_STATUS = 91
INVALID_ECI = 92
INVALID_XID = 93
INVALID_CAVV = 94
INVALID_CAVV_ALGO = 95
INVALID_BRAND = 96
INVALID_REQUEST_ID = 98

OTHER = 99
SENSITIVE_DATA = 999
