
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.0'
version_full = 'd8893584886a593dd6ddcfa1a6930288c7fd8ecc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

