
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.0b5'
version_full = '8f9ac9c01c61a1eb96fd4b43c0eb59f7b68e7268'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

