__version__ = "0.4.18"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.4.18)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '5bafab766693c88095f9f93a2b1944dafdb00a18'
__git_head_subject__ = 'add git commit date option'
__git_head_message__ = ''
__git_dirty_diff__ = ''