
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1'
version_full = '0cc9dfe0ce01e953edb5e2eae20f103bd453fe05'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

