__version__ = "0.2.7"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ef74699f8250b032821cba8952c99cef15424161'
__git_head_subject__ = 'Finished release v0.2.7.'
__git_head_message__ = '* release/v0.2.7:\n  buildout.cfg: changed isolated python version to v2.7.6.20\n  buildout.cfg: changed isolated python version to v2.7.6.19\n  STORAGEMODEL-306 fixing previous commit\n  STORAGEMODEL-306 fixing previous commit\n  HIP-1338 fixing partition prefix on mpath devices on Ubuntu'
__git_dirty_diff__ = ''