
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.0a1'
version_full = '88a89d293fbc8da328ae8298ce77bea2eb900fcb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

