# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created: Tue Oct 14 18:48:56 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1021, 899)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconapp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1001, 821))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formulaire = QtGui.QGridLayout()
        self.formulaire.setObjectName("formulaire")
        self.doublonButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.doublonButton.setObjectName("doublonButton")
        self.formulaire.addWidget(self.doublonButton, 1, 1, 1, 1)
        self.removeLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.removeLabel.setObjectName("removeLabel")
        self.formulaire.addWidget(self.removeLabel, 2, 0, 1, 1)
        self.removeEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.removeEdit.setAutoFillBackground(False)
        self.removeEdit.setStyleSheet("")
        self.removeEdit.setObjectName("removeEdit")
        self.formulaire.addWidget(self.removeEdit, 2, 1, 1, 1)
        self.sourceLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.sourceLabel.setObjectName("sourceLabel")
        self.formulaire.addWidget(self.sourceLabel, 0, 0, 1, 1)
        self.doublonLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.doublonLabel.setObjectName("doublonLabel")
        self.formulaire.addWidget(self.doublonLabel, 1, 0, 1, 1)
        self.sourceButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.sourceButton.setObjectName("sourceButton")
        self.formulaire.addWidget(self.sourceButton, 0, 1, 1, 1)
        self.runButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.runButton.setObjectName("runButton")
        self.formulaire.addWidget(self.runButton, 0, 2, 1, 1)
        self.indicators = QtGui.QHBoxLayout()
        self.indicators.setObjectName("indicators")
        self.hashChoice = QtGui.QHBoxLayout()
        self.hashChoice.setObjectName("hashChoice")
        self.radioSHA1 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioSHA1.setChecked(True)
        self.radioSHA1.setObjectName("radioSHA1")
        self.hashChoice.addWidget(self.radioSHA1)
        self.radioMD5 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioMD5.setObjectName("radioMD5")
        self.hashChoice.addWidget(self.radioMD5)
        self.indicators.addLayout(self.hashChoice)
        self.lcdCounter = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.lcdCounter.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdCounter.setLineWidth(0)
        self.lcdCounter.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdCounter.setObjectName("lcdCounter")
        self.indicators.addWidget(self.lcdCounter)
        self.formulaire.addLayout(self.indicators, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.formulaire)
        self.fLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.fLabel.setObjectName("fLabel")
        self.verticalLayout.addWidget(self.fLabel)
        self.fTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.fTextEdit.setFont(font)
        self.fTextEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.fTextEdit.setObjectName("fTextEdit")
        self.verticalLayout.addWidget(self.fTextEdit)
        self.dLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.dLabel.setObjectName("dLabel")
        self.verticalLayout.addWidget(self.dLabel)
        self.dTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.dTextEdit.setFont(font)
        self.dTextEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.dTextEdit.setObjectName("dTextEdit")
        self.verticalLayout.addWidget(self.dTextEdit)
        self.rLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.rLabel.setObjectName("rLabel")
        self.verticalLayout.addWidget(self.rLabel)
        self.rTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.rTextEdit.setFont(font)
        self.rTextEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.rTextEdit.setObjectName("rTextEdit")
        self.verticalLayout.addWidget(self.rTextEdit)
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 840, 1001, 31))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pydouble 1.3", None, QtGui.QApplication.UnicodeUTF8))
        self.doublonButton.setText(QtGui.QApplication.translate("MainWindow", "Choose duplicate directory", None, QtGui.QApplication.UnicodeUTF8))
        self.removeLabel.setText(QtGui.QApplication.translate("MainWindow", "Extensions to remove", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceLabel.setText(QtGui.QApplication.translate("MainWindow", "Source directory", None, QtGui.QApplication.UnicodeUTF8))
        self.doublonLabel.setText(QtGui.QApplication.translate("MainWindow", "Duplicates directory", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceButton.setText(QtGui.QApplication.translate("MainWindow", "Choose source directory", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSHA1.setText(QtGui.QApplication.translate("MainWindow", "sha1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioMD5.setText(QtGui.QApplication.translate("MainWindow", "md5", None, QtGui.QApplication.UnicodeUTF8))
        self.fLabel.setText(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.dLabel.setText(QtGui.QApplication.translate("MainWindow", "Duplicated files", None, QtGui.QApplication.UnicodeUTF8))
        self.rLabel.setText(QtGui.QApplication.translate("MainWindow", "Removed files", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If you like this software, send me micro bitcoins </span><span style=\" font-size:8pt; font-weight:600;\">158SabxQRumjYkv8kgo1UT34MTYNMXDeF2</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

