
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2'
version_full = '7cdc1bbd98d8ced8baf103514e95a631a1ca6e13'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

