
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0b2'
version_full = 'f7bb81dd154d65f65d4e423e17be2d40f24a17bd'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

