from munin_plugins.plugins.www_analyzers.latencyaggregator import LatencyAggregator
from munin_plugins.plugins.www_analyzers.sizeaggregator import SizeAggregator
from munin_plugins.plugins.www_analyzers.botscounter import BotsCounter
from munin_plugins.plugins.www_analyzers.httpcodescounter import HttpCodesCounter
