
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.1'
version_full = '20e14983f5aa9ec7246cfc262e4645f239a2cbf5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

