
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.17'
version_full = '3226cd514c3a6bf8481cf9f5ac5afbcb546559b8'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

