
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1'
version_full = 'bb4b8ca2479db86363060234b6e44ade3703d197'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

