
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.1'
version_full = '3056a27e3a00d8759f2686ef1b4fe5ac90cbb750'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

