# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FanPage.ui'
#
# Created: Thu Sep 18 22:35:32 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName(_fromUtf8("form"))
        form.resize(568, 549)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(form)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cpu_temperature_group_box = QtGui.QGroupBox(form)
        self.cpu_temperature_group_box.setObjectName(_fromUtf8("cpu_temperature_group_box"))
        self.formLayout_3 = QtGui.QFormLayout(self.cpu_temperature_group_box)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.cpu_temperature_title_label = QtGui.QLabel(self.cpu_temperature_group_box)
        self.cpu_temperature_title_label.setObjectName(_fromUtf8("cpu_temperature_title_label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.cpu_temperature_title_label)
        self.cpu_temperature_label = QtGui.QLabel(self.cpu_temperature_group_box)
        self.cpu_temperature_label.setObjectName(_fromUtf8("cpu_temperature_label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cpu_temperature_label)
        self.verticalLayout.addWidget(self.cpu_temperature_group_box)
        self.hdd_temperature_group_box = QtGui.QGroupBox(form)
        self.hdd_temperature_group_box.setObjectName(_fromUtf8("hdd_temperature_group_box"))
        self.formLayout_2 = QtGui.QFormLayout(self.hdd_temperature_group_box)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hdd_temperature_label = QtGui.QLabel(self.hdd_temperature_group_box)
        self.hdd_temperature_label.setObjectName(_fromUtf8("hdd_temperature_label"))
        self.gridLayout.addWidget(self.hdd_temperature_label, 0, 1, 1, 1)
        self.hdd_temperature_title_label = QtGui.QLabel(self.hdd_temperature_group_box)
        self.hdd_temperature_title_label.setObjectName(_fromUtf8("hdd_temperature_title_label"))
        self.gridLayout.addWidget(self.hdd_temperature_title_label, 0, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout)
        self.verticalLayout.addWidget(self.hdd_temperature_group_box)
        self.fan_spedd_group_box = QtGui.QGroupBox(form)
        self.fan_spedd_group_box.setObjectName(_fromUtf8("fan_spedd_group_box"))
        self.formLayout = QtGui.QFormLayout(self.fan_spedd_group_box)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.fan_speed_label = QtGui.QLabel(self.fan_spedd_group_box)
        self.fan_speed_label.setObjectName(_fromUtf8("fan_speed_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.fan_speed_label)
        self.auto_radio_button = QtGui.QRadioButton(self.fan_spedd_group_box)
        self.auto_radio_button.setObjectName(_fromUtf8("auto_radio_button"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.auto_radio_button)
        self.full_speed_radio_button = QtGui.QRadioButton(self.fan_spedd_group_box)
        self.full_speed_radio_button.setObjectName(_fromUtf8("full_speed_radio_button"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.full_speed_radio_button)
        self.level_radio_button = QtGui.QRadioButton(self.fan_spedd_group_box)
        self.level_radio_button.setChecked(True)
        self.level_radio_button.setObjectName(_fromUtf8("level_radio_button"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.level_radio_button)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fan_level_spin_box = QtGui.QSpinBox(self.fan_spedd_group_box)
        self.fan_level_spin_box.setMaximum(8)
        self.fan_level_spin_box.setObjectName(_fromUtf8("fan_level_spin_box"))
        self.horizontalLayout.addWidget(self.fan_level_spin_box)
        self.fan_level_slider = QtGui.QSlider(self.fan_spedd_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fan_level_slider.sizePolicy().hasHeightForWidth())
        self.fan_level_slider.setSizePolicy(sizePolicy)
        self.fan_level_slider.setMinimumSize(QtCore.QSize(200, 0))
        self.fan_level_slider.setMaximum(8)
        self.fan_level_slider.setSingleStep(1)
        self.fan_level_slider.setPageStep(1)
        self.fan_level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.fan_level_slider.setObjectName(_fromUtf8("fan_level_slider"))
        self.horizontalLayout.addWidget(self.fan_level_slider)
        self.formLayout.setLayout(7, QtGui.QFormLayout.LabelRole, self.horizontalLayout)
        self.disengaged_radio_button = QtGui.QRadioButton(self.fan_spedd_group_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 141, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 147, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.disengaged_radio_button.setPalette(palette)
        self.disengaged_radio_button.setObjectName(_fromUtf8("disengaged_radio_button"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.disengaged_radio_button)
        self.verticalLayout.addWidget(self.fan_spedd_group_box)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.graphic_group_box = QtGui.QGroupBox(form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_group_box.sizePolicy().hasHeightForWidth())
        self.graphic_group_box.setSizePolicy(sizePolicy)
        self.graphic_group_box.setObjectName(_fromUtf8("graphic_group_box"))
        self.graphic_layout = QtGui.QVBoxLayout(self.graphic_group_box)
        self.graphic_layout.setObjectName(_fromUtf8("graphic_layout"))
        self.monitor_check_box = QtGui.QCheckBox(self.graphic_group_box)
        self.monitor_check_box.setObjectName(_fromUtf8("monitor_check_box"))
        self.graphic_layout.addWidget(self.monitor_check_box)
        self.horizontalLayout_2.addWidget(self.graphic_group_box)

        self.retranslateUi(form)
        QtCore.QObject.connect(self.fan_level_spin_box, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.fan_level_slider.setValue)
        QtCore.QObject.connect(self.fan_level_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.fan_level_spin_box.setValue)
        QtCore.QObject.connect(self.level_radio_button, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fan_level_slider.setEnabled)
        QtCore.QObject.connect(self.level_radio_button, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fan_level_spin_box.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        form.setWindowTitle(_translate("form", "Form", None))
        self.cpu_temperature_group_box.setTitle(_translate("form", "CPU Temperature", None))
        self.cpu_temperature_title_label.setText(_translate("form", "Core", None))
        self.cpu_temperature_label.setText(_translate("form", "25 °C", None))
        self.hdd_temperature_group_box.setTitle(_translate("form", "HDD Temperature", None))
        self.hdd_temperature_label.setText(_translate("form", "25 °C", None))
        self.hdd_temperature_title_label.setText(_translate("form", "sda", None))
        self.fan_spedd_group_box.setTitle(_translate("form", "Fan Speed", None))
        self.fan_speed_label.setText(_translate("form", "4000 rpm", None))
        self.auto_radio_button.setText(_translate("form", "auto", None))
        self.full_speed_radio_button.setText(_translate("form", "full-speed", None))
        self.level_radio_button.setText(_translate("form", "level", None))
        self.disengaged_radio_button.setText(_translate("form", "disengaged", None))
        self.graphic_group_box.setTitle(_translate("form", "Graphic", None))
        self.monitor_check_box.setText(_translate("form", "Monitor", None))

