
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.3c2'
version_full = '51ae8a748da830f82ca7a34e477e2359d82c35e9'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

