
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4'
version_full = 'a9c82955006469e4b7aafa4ef6c4ca0f4fa4286f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

