
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.3'
version_full = 'b44103de55cd9d2f347c344c23d71cb87d8d06cb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

