from munin_plugins.plugins.processes_analyzers.cpu import cpu_usage_snsr
from munin_plugins.plugins.processes_analyzers.memory import memory_snsr
from munin_plugins.plugins.processes_analyzers.connections import connections_snsr
from munin_plugins.plugins.processes_analyzers.swap import swap_snsr
from munin_plugins.plugins.processes_analyzers.storage import storages_snsr
from munin_plugins.plugins.processes_analyzers.ios import io_counters_snsr
from munin_plugins.plugins.processes_analyzers.ios import io_counters_abs_snsr
from munin_plugins.plugins.processes_analyzers.threads import threads_snsr
