SUCCESS = 0

CONTACT_CARD_EMITTER = 2
INVALID_ACCEPTER = 3
KEEP_CARD = 4
DO_NOT_HONOR = 5
KEEP_CARD_SPECIFIC_CONDITIONS = 7
APPROVE_AFTER_IDENTIFICATION = 8

INVALID_TRANSACTION = 12
INVALID_AMOUNT = 13
INVALID_HOLDER_NUMBER = 14
INVALID_CARD_EMITTER = 15

USER_CANCEL = 17
REPEAT_IN_FUTURE = 19
INVALID_RESPONSE = 20

FILE_UPDATE_UNSUPPORTED = 24
UNABLE_TO_FIND_IN_FILE = 25
DUPLICATED_OLD_DELETED = 26
EDIT_ERROR_ON_UPDATE = 27
ACCESS_FORBIDDEN = 28
CANT_UPDATE = 29
FORMAT_ERROR = 30

UNKNOWN_BUYER_ID = 31
CARD_EXPIRED = 33
FRAUD_SUSPICION = 34
CARD_EXPIRED_ALT = 38

LOST_CARD = 41
STOLEN_CARD = 43

INSUFFICIENT_PROVISION = 51
CARD_EXPIRED_ALT_2 = 54
INVALID_SECRET = 55
CARD_NOT_IN_FILE = 56
UNAUTHORIZED_HOLDER_TRANSACTION = 57
UNAUTHORIZED_TERMINAL_TRANSACTION = 58
FRAUD_SUSPICION_ALT = 59
CONTACT_BUYER = 60
WITHDRAWL_OUT_OF_LIMIT = 61
SECURITY_RULES_NOT_MET = 63
NO_RESPONSE = 68
TOO_MANY_SECRET_TRIES = 75
HOLDER_IN_OPPOSITION = 76

SYSTEM_FAILURE = 90
UNREACHABLE_CARD_EMITTER = 91
DUPLICATE_TRANSACTION = 94
SYSTEM_ERROR = 96
TIME_DELAYED_GLOBAL_SURVEILLANCE = 97
SYSTEM_UNREACHABLE = 98
INITIATOR_FAILURE = 99
