__version__ = "0.2.8"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '6e5991f8103158b4869d0bc5cc9ce3b3bd5f5bde'
__git_head_subject__ = 'HIP-1278'
__git_head_message__ = ''
__git_dirty_diff__ = ''